/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.buspass.gui.auth_gui;

import javax.swing.JOptionPane;

import com.buspass.auth.UserRegister;
import com.buspass.gui.PanelSwitcher;
import com.buspass.utils.DialogUtils;

/**
 *
 * @author USER
 */
public class RegisterPanel extends javax.swing.JPanel {

    private PanelSwitcher switcher;

    /**
     * Creates new form LoginPanel
     */
    public RegisterPanel() {
        initComponents();
    }

    public void setPanelSwitcher(PanelSwitcher s) {
        this.switcher = s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centerPanel = new javax.swing.JPanel();
        registerFields = new javax.swing.JPanel();
        passwordLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        confirmPasswordLabel = new javax.swing.JLabel();
        confirmPasswordField = new javax.swing.JPasswordField();
        usernameLabel = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();
        userRegisterLabel = new javax.swing.JLabel();
        loginMessagePanel = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1100, 600));
        setMinimumSize(new java.awt.Dimension(1100, 600));
        setPreferredSize(new java.awt.Dimension(1100, 600));

        passwordLabel.setFont(new java.awt.Font("Google Sans", 0, 13)); // NOI18N
        passwordLabel.setText("Password");

        usernameField.setFont(new java.awt.Font("Google Sans", 0, 13)); // NOI18N
        usernameField.addActionListener(this::usernameFieldActionPerformed);

        passwordField.setFont(new java.awt.Font("Google Sans", 0, 13)); // NOI18N
        passwordField.addActionListener(this::passwordFieldActionPerformed);

        confirmPasswordLabel.setFont(new java.awt.Font("Google Sans", 0, 13)); // NOI18N
        confirmPasswordLabel.setText("Confirm Password");

        confirmPasswordField.setFont(new java.awt.Font("Google Sans", 0, 13)); // NOI18N
        confirmPasswordField.addActionListener(this::confirmPasswordFieldActionPerformed);

        usernameLabel.setFont(new java.awt.Font("Google Sans", 0, 13)); // NOI18N
        usernameLabel.setText("Username");

        registerButton.setFont(new java.awt.Font("Google Sans", 0, 16)); // NOI18N
        registerButton.setText("Register");
        registerButton.addActionListener(this::registerButtonActionPerformed);

        javax.swing.GroupLayout registerFieldsLayout = new javax.swing.GroupLayout(registerFields);
        registerFields.setLayout(registerFieldsLayout);
        registerFieldsLayout.setHorizontalGroup(
            registerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerFieldsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(registerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(registerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(passwordLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(usernameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(confirmPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        registerFieldsLayout.setVerticalGroup(
            registerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerFieldsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(usernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(confirmPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        userRegisterLabel.setFont(new java.awt.Font("Lexend Medium", 0, 18)); // NOI18N
        userRegisterLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userRegisterLabel.setText("REGISTER");

        loginLabel.setFont(new java.awt.Font("Google Sans", 0, 13)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(0, 0, 255));
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        loginLabel.setText("Login Now");
        loginLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginLabelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginLabelMousePressed(evt);
            }
        });

        messageLabel.setFont(new java.awt.Font("Google Sans", 0, 13)); // NOI18N
        messageLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        messageLabel.setText("Already have an account?");

        javax.swing.GroupLayout loginMessagePanelLayout = new javax.swing.GroupLayout(loginMessagePanel);
        loginMessagePanel.setLayout(loginMessagePanelLayout);
        loginMessagePanelLayout.setHorizontalGroup(
            loginMessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginMessagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        loginMessagePanelLayout.setVerticalGroup(
            loginMessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginMessagePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loginMessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout centerPanelLayout = new javax.swing.GroupLayout(centerPanel);
        centerPanel.setLayout(centerPanelLayout);
        centerPanelLayout.setHorizontalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(centerPanelLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(userRegisterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(loginMessagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        centerPanelLayout.setVerticalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(userRegisterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginMessagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        add(centerPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:

        UserRegister userRegister = new UserRegister();

        String username = usernameField.getText();
        String plainPW = new String(passwordField.getPassword());
        String confirmPlainPW = new String(confirmPasswordField.getPassword());

        int result = userRegister.attemptRegister(username, plainPW, confirmPlainPW);
        
        passwordField.setText("");
        confirmPasswordField.setText("");

        switch(result) {
            case -3:
                DialogUtils.showDialogInvalidPWs();
                break;
            case -2:
                DialogUtils.showDialogUnidenticalPWs();
                break;
            case -1:
                DialogUtils.showDialogInvalidUsername();
                break;
            case 0:
                DialogUtils.showDialogUserAlreadyExists(username);
                clearFields();
                break;
            case 1:
                DialogUtils.showDialogRegistrationSuccess(username);
                clearFields();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void confirmPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPasswordFieldActionPerformed

    private void loginLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLabelMouseClicked
        
    }//GEN-LAST:event_loginLabelMouseClicked

    private void loginLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLabelMousePressed
        if (switcher != null) {
            switcher.showPanel(AuthPanel.LOGIN);
        }
    }//GEN-LAST:event_loginLabelMousePressed

    public void clearFields() {
        usernameField.setText("");
        passwordField.setText("");
        confirmPasswordField.setText("");
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JLabel confirmPasswordLabel;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel loginMessagePanel;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JPanel registerFields;
    private javax.swing.JLabel userRegisterLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
