/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.buspass.gui.auth_gui;

import javax.swing.JOptionPane;

import com.buspass.gui.PanelSwitcher;
import com.buspass.queries.UserService;
import com.buspass.utils.AuthUtils;
import com.buspass.utils.DialogUtils;
import com.buspass.utils.GuiUtils;

/**
 *
 * @author USER
 */
public class ResetPasswordPanel extends javax.swing.JPanel {

    PanelSwitcher switcher;

    /**
     * Creates new form LoginPanel
     */
    public ResetPasswordPanel() {
        initComponents();
    }

    public void setPanelSwitcher(PanelSwitcher switcher) {
        this.switcher = switcher;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userRegisterLabel = new javax.swing.JLabel();
        registerFields = new javax.swing.JPanel();
        resetPasswordButton = new javax.swing.JButton();
        passwordLabel = new javax.swing.JLabel();
        userPasswordField = new javax.swing.JPasswordField();
        confirmPasswordLabel = new javax.swing.JLabel();
        confirmPasswordField = new javax.swing.JPasswordField();
        usernameField = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        loginMessagePanel = new javax.swing.JPanel();
        backLoginLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1100, 600));
        setMinimumSize(new java.awt.Dimension(1100, 600));
        setPreferredSize(new java.awt.Dimension(1100, 600));

        userRegisterLabel.setFont(GuiUtils.LEXEND_MEDIUM_18);
        userRegisterLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userRegisterLabel.setText("RESET PASSWORD");

        resetPasswordButton.setFont(GuiUtils.GOOGLE_SANS_16);
        resetPasswordButton.setText("Reset Password");
        resetPasswordButton.addActionListener(this::resetPasswordButtonActionPerformed);

        passwordLabel.setFont(GuiUtils.GOOGLE_SANS_14);
        passwordLabel.setText("Password");

        userPasswordField.setFont(GuiUtils.GOOGLE_SANS_14);
        userPasswordField.addActionListener(this::userPasswordFieldActionPerformed);

        confirmPasswordLabel.setFont(GuiUtils.GOOGLE_SANS_14);
        confirmPasswordLabel.setText("Confirm Password");

        confirmPasswordField.setFont(GuiUtils.GOOGLE_SANS_14);
        confirmPasswordField.addActionListener(this::confirmPasswordFieldActionPerformed);

        usernameField.setFont(GuiUtils.GOOGLE_SANS_14);
        usernameField.addActionListener(this::usernameFieldActionPerformed);

        usernameLabel.setFont(GuiUtils.GOOGLE_SANS_14);
        usernameLabel.setText("Username");

        javax.swing.GroupLayout registerFieldsLayout = new javax.swing.GroupLayout(registerFields);
        registerFields.setLayout(registerFieldsLayout);
        registerFieldsLayout.setHorizontalGroup(
            registerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerFieldsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(registerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(registerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(resetPasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(userPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(passwordLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(usernameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(confirmPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        registerFieldsLayout.setVerticalGroup(
            registerFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerFieldsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(usernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(confirmPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(resetPasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        backLoginLabel.setFont(GuiUtils.GOOGLE_SANS_14);
        backLoginLabel.setForeground(new java.awt.Color(0, 0, 255));
        backLoginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backLoginLabel.setText("Back to Login");
        backLoginLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLoginLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout loginMessagePanelLayout = new javax.swing.GroupLayout(loginMessagePanel);
        loginMessagePanel.setLayout(loginMessagePanelLayout);
        loginMessagePanelLayout.setHorizontalGroup(
            loginMessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginMessagePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backLoginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        loginMessagePanelLayout.setVerticalGroup(
            loginMessagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginMessagePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backLoginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(415, 415, 415)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loginMessagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registerFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(415, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userRegisterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(459, 459, 459))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(userRegisterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registerFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginMessagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void resetPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetPasswordButtonActionPerformed
        UserService userService = new UserService();

        String username = usernameField.getText();
        String plainPW = new String(userPasswordField.getPassword());
        String confirmPlainPW = new String(confirmPasswordField.getPassword());

        int userId = userService.getIdByUsername(username);
        if (userId <= 0) {
            JOptionPane.showMessageDialog(null, "User with Username: " + username + " does not exist.", "User not found", JOptionPane.DEFAULT_OPTION);
            return;
        }

        if (!AuthUtils.isValidPassword(plainPW)) {
            DialogUtils.showDialogInvalidPWs();
            return;
        }

        if (plainPW.compareTo(confirmPlainPW) != 0) {
            DialogUtils.showDialogUnidenticalPWs();
            return;
        }

        boolean ok = userService.updatePassword(userId, plainPW);

        if (ok) 
            JOptionPane.showMessageDialog(null, "Password has been reset", "Reset Success", JOptionPane.DEFAULT_OPTION);
        else
            JOptionPane.showMessageDialog(null, "Failed to reset Password", "Reset Failed", JOptionPane.DEFAULT_OPTION);

        clearFields();
        
    }//GEN-LAST:event_resetPasswordButtonActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void userPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userPasswordFieldActionPerformed

    private void confirmPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPasswordFieldActionPerformed

    private void backLoginLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLoginLabelMouseClicked
        if (switcher != null) {
            switcher.showPanel(AuthPanel.LOGIN);
        }
    }//GEN-LAST:event_backLoginLabelMouseClicked

    public void clearFields() {
        usernameField.setText("");
        userPasswordField.setText("");
        confirmPasswordField.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backLoginLabel;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JLabel confirmPasswordLabel;
    private javax.swing.JPanel loginMessagePanel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPanel registerFields;
    private javax.swing.JButton resetPasswordButton;
    private javax.swing.JPasswordField userPasswordField;
    private javax.swing.JLabel userRegisterLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
