/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.buspass.gui.app_gui.etc;

import com.buspass.gui.app_gui.dialogs.PurchaseTicketPanel;
import com.buspass.queries.TripQuery;

/**
 *
 * @author USER
 */
public class TicketAction extends javax.swing.JPanel {

    /**
     * Creates new form TicketAction
     */

    private TripInject tripInject;

    public TicketAction(TripInject tripInject) {
        initComponents();
        this.tripInject = tripInject;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buyButton = new javax.swing.JButton();

        buyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/buspass/gui/app_gui/etc/buying_icon.png"))); // NOI18N
        buyButton.setMaximumSize(new java.awt.Dimension(48, 48));
        buyButton.setMinimumSize(new java.awt.Dimension(48, 48));
        buyButton.setPreferredSize(new java.awt.Dimension(48, 48));
        buyButton.addActionListener(this::buyButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyButtonActionPerformed
        java.awt.Window owner = javax.swing.SwingUtilities.getWindowAncestor(this);
        final javax.swing.JDialog dialog = new javax.swing.JDialog(owner, "Purchase Ticket for Trip",
                java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        TripQuery tq = (tripInject == null) ? null : tripInject.getTripQuery();
        PurchaseTicketPanel panel = new PurchaseTicketPanel(tq);
        // if TripID was injected, populate the purchase panel
        Integer injectedId = (tripInject == null) ? null : tripInject.getTripID();
        if (injectedId != null) {
            panel.setTripId(String.valueOf(injectedId));
            // optionally fetch fare and populate
            try {
                Double fare = tq == null ? null : tq.getFareByTripId(injectedId);
                if (fare != null) panel.setFare(String.format("%.2f", fare));
            } catch (Exception e) {
                // ignore fare fetch errors
            }
        }
        dialog.setDefaultCloseOperation(javax.swing.JDialog.DISPOSE_ON_CLOSE);
        dialog.setContentPane(panel);
        dialog.pack();
        // center the purchase dialog on the screen
        dialog.setLocationRelativeTo(null);
        panel.getCancelButton().addActionListener(e -> dialog.dispose());
        panel.getPurchaseButton().addActionListener(e -> {

            // LinkedHashMap<String, Object> trip = 


            dialog.dispose();
        } 
        );

        dialog.setVisible(true); // blocks until closed
    }//GEN-LAST:event_buyButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyButton;
    // End of variables declaration//GEN-END:variables
}
