/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.buspass.gui.app_gui;

import com.buspass.auth.UserLoginSession;
import com.buspass.gui.PanelSwitcher;
import com.buspass.gui.app_gui.admin.BusesPanel;
import com.buspass.gui.app_gui.admin.UsersPanel;
import java.awt.BorderLayout;

import javax.swing.JPanel;

/**
 *
 * @author USER
 */
public class MainPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     */
    UserLoginSession userLoginSession;

    private PanelSwitcher switcher;

    private UsersPanel usersPanel;
    private JPanel[] panels = new JPanel[9];

    private static final int USERS_PANEL = 0;
    private static final int BUSES_PANEL = 1;

    public void setPanelSwitcher(PanelSwitcher s) {
        this.switcher = s;
    }

    public MainPanel(UserLoginSession userLoginSession) {
        initComponents();
        scrollPane.getVerticalScrollBar().setUnitIncrement(20);

        this.userLoginSession = userLoginSession;
        // routesButton.setVisible(false);
        // tripButton.setVisible(false);

        panels[USERS_PANEL] = new UsersPanel();      
        panels[BUSES_PANEL] = new BusesPanel();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        middlePanel = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        buttonPanel = new javax.swing.JPanel();
        mainButton = new javax.swing.JButton();
        usersButton = new javax.swing.JButton();
        driversButton = new javax.swing.JButton();
        busesButton = new javax.swing.JButton();
        routesButton = new javax.swing.JButton();
        tripButton = new javax.swing.JButton();
        ticketsButton = new javax.swing.JButton();
        paymentsButton = new javax.swing.JButton();
        customSqlButton = new javax.swing.JButton();
        topPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        permissionLabel = new javax.swing.JLabel();
        permissionTextLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(240, 240, 240));
        setMinimumSize(new java.awt.Dimension(1100, 600));
        setPreferredSize(new java.awt.Dimension(1100, 600));

        middlePanel.setPreferredSize(new java.awt.Dimension(943, 545));

        javax.swing.GroupLayout middlePanelLayout = new javax.swing.GroupLayout(middlePanel);
        middlePanel.setLayout(middlePanelLayout);
        middlePanelLayout.setHorizontalGroup(
            middlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 943, Short.MAX_VALUE)
        );
        middlePanelLayout.setVerticalGroup(
            middlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        scrollPane.setBackground(new java.awt.Color(220, 220, 220));
        scrollPane.setForeground(new java.awt.Color(220, 220, 220));
        scrollPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        scrollPane.setHorizontalScrollBar(null);

        buttonPanel.setMaximumSize(new java.awt.Dimension(85, 33));
        buttonPanel.setName(""); // NOI18N
        buttonPanel.setLayout(new javax.swing.BoxLayout(buttonPanel, javax.swing.BoxLayout.Y_AXIS));

        mainButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mainButton.setText("Main");
        mainButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mainButton.setMaximumSize(new java.awt.Dimension(125, 40));
        mainButton.setMinimumSize(new java.awt.Dimension(125, 40));
        mainButton.setPreferredSize(new java.awt.Dimension(125, 40));
        mainButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(mainButton);

        usersButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usersButton.setText("Users");
        usersButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        usersButton.setMaximumSize(new java.awt.Dimension(125, 40));
        usersButton.setMinimumSize(new java.awt.Dimension(125, 40));
        usersButton.setPreferredSize(new java.awt.Dimension(125, 40));
        usersButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(usersButton);

        driversButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        driversButton.setText("Drivers");
        driversButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        driversButton.setMaximumSize(new java.awt.Dimension(125, 40));
        driversButton.setMinimumSize(new java.awt.Dimension(125, 40));
        driversButton.setPreferredSize(new java.awt.Dimension(125, 40));
        driversButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                driversButtonMouseClicked(evt);
            }
        });
        driversButton.addActionListener(this::driversButtonActionPerformed);
        buttonPanel.add(driversButton);

        busesButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        busesButton.setText("Buses");
        busesButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        busesButton.setMaximumSize(new java.awt.Dimension(125, 40));
        busesButton.setMinimumSize(new java.awt.Dimension(125, 40));
        busesButton.setPreferredSize(new java.awt.Dimension(125, 40));
        busesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busesButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(busesButton);

        routesButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        routesButton.setText("Routes");
        routesButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        routesButton.setMaximumSize(new java.awt.Dimension(125, 40));
        routesButton.setMinimumSize(new java.awt.Dimension(125, 40));
        routesButton.setPreferredSize(new java.awt.Dimension(125, 40));
        routesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                routesButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(routesButton);

        tripButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tripButton.setText("Trips");
        tripButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tripButton.setMaximumSize(new java.awt.Dimension(125, 40));
        tripButton.setMinimumSize(new java.awt.Dimension(125, 40));
        tripButton.setPreferredSize(new java.awt.Dimension(125, 40));
        tripButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tripButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(tripButton);

        ticketsButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ticketsButton.setText("Tickets");
        ticketsButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ticketsButton.setMaximumSize(new java.awt.Dimension(125, 40));
        ticketsButton.setMinimumSize(new java.awt.Dimension(125, 40));
        ticketsButton.setPreferredSize(new java.awt.Dimension(125, 40));
        ticketsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ticketsButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(ticketsButton);

        paymentsButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        paymentsButton.setText("Payments");
        paymentsButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        paymentsButton.setMaximumSize(new java.awt.Dimension(125, 40));
        paymentsButton.setMinimumSize(new java.awt.Dimension(125, 40));
        paymentsButton.setPreferredSize(new java.awt.Dimension(125, 40));
        paymentsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paymentsButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(paymentsButton);

        customSqlButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        customSqlButton.setText("CustomSQL");
        customSqlButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        customSqlButton.setMaximumSize(new java.awt.Dimension(125, 40));
        customSqlButton.setMinimumSize(new java.awt.Dimension(125, 40));
        customSqlButton.setPreferredSize(new java.awt.Dimension(125, 40));
        customSqlButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customSqlButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(customSqlButton);

        scrollPane.setViewportView(buttonPanel);

        topPanel.setBackground(new java.awt.Color(220, 220, 220));
        topPanel.setPreferredSize(new java.awt.Dimension(100, 70));

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(0, 0, 255));
        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        usernameLabel.setText("Username");
        usernameLabel.setToolTipText("Click to go to your User Panel");

        permissionLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        permissionLabel.setText("Session Permission: ");

        permissionTextLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        permissionTextLabel.setText("Passenger");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(permissionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(permissionTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(permissionTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(permissionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(middlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(topPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                    .addComponent(middlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void driversButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driversButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_driversButtonActionPerformed

    private void mainButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mainButtonMouseClicked

    private void usersButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersButtonMouseClicked
        // TODO add your handling code here:
        switchMiddlePanel(USERS_PANEL);
    }//GEN-LAST:event_usersButtonMouseClicked

    private void driversButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_driversButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_driversButtonMouseClicked

    private void busesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busesButtonMouseClicked
        // TODO add your handling code here:
        switchMiddlePanel(BUSES_PANEL);
    }//GEN-LAST:event_busesButtonMouseClicked

    private void routesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_routesButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_routesButtonMouseClicked

    private void tripButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tripButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tripButtonMouseClicked

    private void ticketsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticketsButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ticketsButtonMouseClicked

    private void paymentsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentsButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentsButtonMouseClicked

    private void customSqlButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customSqlButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_customSqlButtonMouseClicked

    private void switchMiddlePanel(int childPanel) {
        // embed the UsersPanel into the middlePanel
        try {
            middlePanel.removeAll();
            middlePanel.setLayout(new BorderLayout());
            middlePanel.add(panels[childPanel], BorderLayout.CENTER);
            middlePanel.revalidate();
            middlePanel.repaint();
        } catch (Exception e) {
            // keep UI resilient if UsersPanel construction fails
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton busesButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton customSqlButton;
    private javax.swing.JButton driversButton;
    private javax.swing.JButton mainButton;
    private javax.swing.JPanel middlePanel;
    private javax.swing.JButton paymentsButton;
    private javax.swing.JLabel permissionLabel;
    private javax.swing.JLabel permissionTextLabel;
    private javax.swing.JButton routesButton;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JButton ticketsButton;
    private javax.swing.JPanel topPanel;
    private javax.swing.JButton tripButton;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JButton usersButton;
    // End of variables declaration//GEN-END:variables
}
