/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.buspass.gui.app_gui;

import com.buspass.gui.app_gui.middle_panels.TicketsPanel;
import com.buspass.gui.app_gui.middle_panels.PaymentsPanel;
import com.buspass.gui.app_gui.middle_panels.DriversPanel;
import com.buspass.gui.app_gui.middle_panels.InMiddlePanel;
import com.buspass.gui.app_gui.middle_panels.BusesPanel;
import com.buspass.gui.app_gui.middle_panels.RoutesPanel;
import com.buspass.gui.app_gui.middle_panels.UsersPanel;
import com.buspass.utils.GuiUtils;
import com.buspass.gui.app_gui.middle_panels.TripsPanel;
import com.buspass.auth.UserLoginSession;
import com.buspass.auth.UserRegister;
import com.buspass.gui.AppPanel;
import com.buspass.gui.PanelSwitcher;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author USER
 */
public class MainPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     */
    UserLoginSession userLoginSession;

    public static final int NUMBER_OF_MIDDLE_PANELS = 8;
    public static final int NUMBER_OF_INMIDDLE_PANELS = 8;
    private static final int USERS_PANEL      = 1;
    private static final int DRIVERS_PANEL    = 2;
    private static final int BUSES_PANEL      = 3;
    private static final int ROUTES_PANEL     = 4;
    private static final int TRIPS_PANEL      = 5;
    private static final int TICKETS_PANEL    = 6;
    private static final int PAYMENTS_PANEL   = 7;

    private PanelSwitcher switcher;

    private JPanel[] panels = new JPanel[NUMBER_OF_MIDDLE_PANELS];
    private InMiddlePanel[] middlePanels = new InMiddlePanel[NUMBER_OF_INMIDDLE_PANELS];

    public void setPanelSwitcher(PanelSwitcher s) {
        this.switcher = s;
    }

    public MainPanel(UserLoginSession userLoginSession) {
        initComponents();
        scrollPane.getVerticalScrollBar().setUnitIncrement(20);

        this.userLoginSession = userLoginSession;

        UsersPanel    usersPanel    = new UsersPanel();
        DriversPanel  driversPanel  = new DriversPanel();
        BusesPanel    busesPanel    = new BusesPanel();
        RoutesPanel   routesPanel   = new RoutesPanel(); 
        TripsPanel    tripsPanel    = new TripsPanel(userLoginSession);
        TicketsPanel  ticketsPanel  = new TicketsPanel(userLoginSession);
        PaymentsPanel paymentsPanel = new PaymentsPanel(userLoginSession);

        panels[USERS_PANEL]      = usersPanel;
        panels[DRIVERS_PANEL]    = driversPanel;
        panels[BUSES_PANEL]      = busesPanel;   
        panels[ROUTES_PANEL]     = routesPanel;  
        panels[TRIPS_PANEL]      = tripsPanel;   
        panels[TICKETS_PANEL]    = ticketsPanel; 
        panels[PAYMENTS_PANEL]   = paymentsPanel;

        middlePanels[USERS_PANEL]      = usersPanel;
        middlePanels[DRIVERS_PANEL]    = driversPanel; 
        middlePanels[BUSES_PANEL]      = busesPanel;   
        middlePanels[ROUTES_PANEL]     = routesPanel;  
        middlePanels[TRIPS_PANEL]      = tripsPanel;   
        middlePanels[TICKETS_PANEL]    = ticketsPanel; 
        middlePanels[PAYMENTS_PANEL]   = paymentsPanel;

        // Hide "Main" button since its unused
        mainButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        middlePanel = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        buttonPanel = new javax.swing.JPanel();
        mainButton = new javax.swing.JButton();
        usersButton = new javax.swing.JButton();
        driversButton = new javax.swing.JButton();
        busesButton = new javax.swing.JButton();
        routesButton = new javax.swing.JButton();
        tripButton = new javax.swing.JButton();
        ticketsButton = new javax.swing.JButton();
        paymentsButton = new javax.swing.JButton();
        topPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        permissionLabel = new javax.swing.JLabel();
        permissionTextLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(240, 240, 240));
        setMinimumSize(new java.awt.Dimension(1100, 600));
        setPreferredSize(new java.awt.Dimension(1100, 600));

        middlePanel.setPreferredSize(new java.awt.Dimension(943, 545));

        javax.swing.GroupLayout middlePanelLayout = new javax.swing.GroupLayout(middlePanel);
        middlePanel.setLayout(middlePanelLayout);
        middlePanelLayout.setHorizontalGroup(
            middlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        middlePanelLayout.setVerticalGroup(
            middlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
        );

        scrollPane.setBackground(new java.awt.Color(220, 220, 220));
        scrollPane.setForeground(new java.awt.Color(220, 220, 220));
        scrollPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        scrollPane.setHorizontalScrollBar(null);

        buttonPanel.setMaximumSize(new java.awt.Dimension(85, 33));
        buttonPanel.setName(""); // NOI18N
        buttonPanel.setLayout(new javax.swing.BoxLayout(buttonPanel, javax.swing.BoxLayout.Y_AXIS));

        mainButton.setFont(GuiUtils.GOOGLE_SANS_14);
        mainButton.setText("Main");
        mainButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mainButton.setMaximumSize(new java.awt.Dimension(125, 40));
        mainButton.setMinimumSize(new java.awt.Dimension(125, 40));
        mainButton.setPreferredSize(new java.awt.Dimension(125, 40));
        mainButton.addActionListener(this::mainButtonActionPerformed);
        buttonPanel.add(mainButton);

        usersButton.setFont(GuiUtils.GOOGLE_SANS_14);
        usersButton.setText("Users");
        usersButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        usersButton.setMaximumSize(new java.awt.Dimension(125, 40));
        usersButton.setMinimumSize(new java.awt.Dimension(125, 40));
        usersButton.setPreferredSize(new java.awt.Dimension(125, 40));
        usersButton.addActionListener(this::usersButtonActionPerformed);
        buttonPanel.add(usersButton);

        driversButton.setFont(GuiUtils.GOOGLE_SANS_14);
        driversButton.setText("Drivers");
        driversButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        driversButton.setMaximumSize(new java.awt.Dimension(125, 40));
        driversButton.setMinimumSize(new java.awt.Dimension(125, 40));
        driversButton.setPreferredSize(new java.awt.Dimension(125, 40));
        driversButton.addActionListener(this::driversButtonActionPerformed);
        buttonPanel.add(driversButton);

        busesButton.setFont(GuiUtils.GOOGLE_SANS_14);
        busesButton.setText("Buses");
        busesButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        busesButton.setMaximumSize(new java.awt.Dimension(125, 40));
        busesButton.setMinimumSize(new java.awt.Dimension(125, 40));
        busesButton.setPreferredSize(new java.awt.Dimension(125, 40));
        busesButton.addActionListener(this::busesButtonActionPerformed);
        buttonPanel.add(busesButton);

        routesButton.setFont(GuiUtils.GOOGLE_SANS_14);
        routesButton.setText("Routes");
        routesButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        routesButton.setMaximumSize(new java.awt.Dimension(125, 40));
        routesButton.setMinimumSize(new java.awt.Dimension(125, 40));
        routesButton.setPreferredSize(new java.awt.Dimension(125, 40));
        routesButton.addActionListener(this::routesButtonActionPerformed);
        buttonPanel.add(routesButton);

        tripButton.setFont(GuiUtils.GOOGLE_SANS_14);
        tripButton.setText("Trips");
        tripButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tripButton.setMaximumSize(new java.awt.Dimension(125, 40));
        tripButton.setMinimumSize(new java.awt.Dimension(125, 40));
        tripButton.setPreferredSize(new java.awt.Dimension(125, 40));
        tripButton.addActionListener(this::tripButtonActionPerformed);
        buttonPanel.add(tripButton);

        ticketsButton.setFont(GuiUtils.GOOGLE_SANS_14);
        ticketsButton.setText("Tickets");
        ticketsButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ticketsButton.setMaximumSize(new java.awt.Dimension(125, 40));
        ticketsButton.setMinimumSize(new java.awt.Dimension(125, 40));
        ticketsButton.setPreferredSize(new java.awt.Dimension(125, 40));
        ticketsButton.addActionListener(this::ticketsButtonActionPerformed);
        buttonPanel.add(ticketsButton);

        paymentsButton.setFont(GuiUtils.GOOGLE_SANS_14);
        paymentsButton.setText("Payments");
        paymentsButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        paymentsButton.setMaximumSize(new java.awt.Dimension(125, 40));
        paymentsButton.setMinimumSize(new java.awt.Dimension(125, 40));
        paymentsButton.setPreferredSize(new java.awt.Dimension(125, 40));
        paymentsButton.addActionListener(this::paymentsButtonActionPerformed);
        buttonPanel.add(paymentsButton);

        scrollPane.setViewportView(buttonPanel);

        topPanel.setBackground(new java.awt.Color(220, 220, 220));
        topPanel.setPreferredSize(new java.awt.Dimension(100, 70));

        usernameLabel.setFont(GuiUtils.GOOGLE_SANS_15);
        usernameLabel.setForeground(new java.awt.Color(0, 0, 255));
        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        usernameLabel.setText("Username");
        usernameLabel.setToolTipText("Click to go to your User Panel");
        usernameLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameLabelMouseClicked(evt);
            }
        });

        permissionLabel.setFont(GuiUtils.GOOGLE_SANS_15);
        permissionLabel.setText("Session Permission: ");

        permissionTextLabel.setFont(GuiUtils.GOOGLE_SANS_15);
        permissionTextLabel.setText("Passenger");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(permissionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(permissionTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 754, Short.MAX_VALUE)
                .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(permissionTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(permissionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(middlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 949, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(topPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(middlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(scrollPane)))
        );
    }// </editor-fold>//GEN-END:initComponents

        
    private void usersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersButtonActionPerformed
        switchMiddlePanel(USERS_PANEL);
    }//GEN-LAST:event_usersButtonActionPerformed

    private void driversButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driversButtonActionPerformed
        switchMiddlePanel(DRIVERS_PANEL);
    }//GEN-LAST:event_driversButtonActionPerformed

    private void busesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busesButtonActionPerformed
        switchMiddlePanel(BUSES_PANEL);
    }//GEN-LAST:event_busesButtonActionPerformed

    private void routesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routesButtonActionPerformed
        switchMiddlePanel(ROUTES_PANEL);
    }//GEN-LAST:event_routesButtonActionPerformed

    private void tripButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tripButtonActionPerformed
        switchMiddlePanel(TRIPS_PANEL);
    }//GEN-LAST:event_tripButtonActionPerformed

    private void ticketsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketsButtonActionPerformed
        switchMiddlePanel(TICKETS_PANEL);
    }//GEN-LAST:event_ticketsButtonActionPerformed

    private void paymentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentsButtonActionPerformed
        switchMiddlePanel(PAYMENTS_PANEL);
    }//GEN-LAST:event_paymentsButtonActionPerformed

    private void usernameLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameLabelMouseClicked
        switcher.showPanel(AppPanel.MY_ACCOUNT);
    }//GEN-LAST:event_usernameLabelMouseClicked

    private void mainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainButtonActionPerformed
        // switchMiddlePanel(USERS_PANEL);
    }//GEN-LAST:event_mainButtonActionPerformed

    private void switchMiddlePanel(int childPanel) {
        // embed the UsersPanel into the middlePanel
        try {
            middlePanel.removeAll();
            middlePanel.setLayout(new BorderLayout());
            middlePanel.add(panels[childPanel], BorderLayout.CENTER);
            middlePanel.revalidate();
            middlePanel.repaint();
        } catch (Exception e) {
            // keep UI resilient if UsersPanel construction fails
            e.printStackTrace();
        }
    }

    public void updatePanel() {
        usernameLabel.setText(userLoginSession.getUsername());
        updateButtons();
    }

    private void updateButtons() {
        int userRoleID = userLoginSession.getUserRoleId();
        if (userRoleID == 1) {
            permissionTextLabel.setText("Passenger");
            hideAdminButtons();
        }
        else if (userRoleID == 2) {
            permissionTextLabel.setText("Admin");
            showAdminButtons();            
        }
    }

    private void showAdminButtons() {
        for (int i = 1; i < NUMBER_OF_INMIDDLE_PANELS; i++) {
            middlePanels[i].showAdminButtons();
        }
    }

    private void hideAdminButtons() {
        for (int i = 1; i < NUMBER_OF_INMIDDLE_PANELS; i++) {
            middlePanels[i].hideAdminButtons();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton busesButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton driversButton;
    private javax.swing.JButton mainButton;
    private javax.swing.JPanel middlePanel;
    private javax.swing.JButton paymentsButton;
    private javax.swing.JLabel permissionLabel;
    private javax.swing.JLabel permissionTextLabel;
    private javax.swing.JButton routesButton;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JButton ticketsButton;
    private javax.swing.JPanel topPanel;
    private javax.swing.JButton tripButton;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JButton usersButton;
    // End of variables declaration//GEN-END:variables
}
