/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.buspass.gui.app_gui;

import java.awt.Panel;

import com.buspass.auth.UserLoginSession;
import com.buspass.queries.UserService;
import com.buspass.utils.AuthUtils;
import com.buspass.utils.DialogUtils;
import com.buspass.utils.GuiUtils;
import com.buspass.gui.AppPanel;
import com.buspass.gui.PanelSwitcher;

/**
 *
 * @author USER
 */
public class MyAccountPanel extends javax.swing.JPanel {

    /**
     * Creates new form MyAccountPanel
     */
    UserLoginSession userLoginSession;
    PanelSwitcher appPanelSwitcher;
    final String USER_ROLE_PREFIX = "You logged in as an ";

    public MyAccountPanel(UserLoginSession userLoginSession) {
        initComponents();
        this.userLoginSession = userLoginSession;
        userIdField.setEnabled(false);
    }

    private UserService userService = new UserService();

    public void setPanelSwitcher(PanelSwitcher switcher) {
        this.appPanelSwitcher = switcher;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        middlePanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        leftPanel = new javax.swing.JPanel();
        userIdLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        fullNameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        userIdField = new javax.swing.JTextField();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        fullNameField = new javax.swing.JTextField();
        ageField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        optionPanel = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        discardButton = new javax.swing.JButton();
        signOutButton = new javax.swing.JButton();
        permissionLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1100, 600));
        setMinimumSize(new java.awt.Dimension(1100, 600));

        headerPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        headerLabel.setFont(GuiUtils.LEXEND_MEDIUM_18);
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("MY USER INFORMATION");
        headerPanel.add(headerLabel);

        leftPanel.setLayout(new java.awt.GridLayout(9, 1, 0, 5));

        userIdLabel.setFont(GuiUtils.GOOGLE_SANS_14);
        userIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userIdLabel.setText("UserID");
        leftPanel.add(userIdLabel);

        usernameLabel.setFont(GuiUtils.GOOGLE_SANS_14);
        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameLabel.setText("Username");
        leftPanel.add(usernameLabel);

        passwordLabel.setFont(GuiUtils.GOOGLE_SANS_14);
        passwordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordLabel.setText("Password");
        leftPanel.add(passwordLabel);

        fullNameLabel.setFont(GuiUtils.GOOGLE_SANS_14);
        fullNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fullNameLabel.setText("Full Name");
        leftPanel.add(fullNameLabel);

        ageLabel.setFont(GuiUtils.GOOGLE_SANS_14);
        ageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ageLabel.setText("Age");
        leftPanel.add(ageLabel);

        phoneLabel.setFont(GuiUtils.GOOGLE_SANS_14);
        phoneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        phoneLabel.setText("Phone Number");
        leftPanel.add(phoneLabel);

        addressLabel.setFont(GuiUtils.GOOGLE_SANS_14);
        addressLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addressLabel.setText("Address");
        leftPanel.add(addressLabel);

        rightPanel.setLayout(new java.awt.GridLayout(9, 1, 0, 5));

        userIdField.setFont(GuiUtils.GOOGLE_SANS_14);
        userIdField.addActionListener(this::userIdFieldActionPerformed);
        rightPanel.add(userIdField);

        usernameField.setFont(GuiUtils.GOOGLE_SANS_14);
        rightPanel.add(usernameField);

        passwordField.setFont(GuiUtils.GOOGLE_SANS_14);
        passwordField.addActionListener(this::passwordFieldActionPerformed);
        rightPanel.add(passwordField);

        fullNameField.setFont(GuiUtils.GOOGLE_SANS_14);
        rightPanel.add(fullNameField);

        ageField.setFont(GuiUtils.GOOGLE_SANS_14);
        rightPanel.add(ageField);

        phoneField.setFont(GuiUtils.GOOGLE_SANS_14);
        rightPanel.add(phoneField);

        addressField.setFont(GuiUtils.GOOGLE_SANS_14);
        rightPanel.add(addressField);

        javax.swing.GroupLayout middlePanelLayout = new javax.swing.GroupLayout(middlePanel);
        middlePanel.setLayout(middlePanelLayout);
        middlePanelLayout.setHorizontalGroup(
            middlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(middlePanelLayout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );
        middlePanelLayout.setVerticalGroup(
            middlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, middlePanelLayout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(middlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        optionPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        saveButton.setFont(GuiUtils.GOOGLE_SANS_16);
        saveButton.setForeground(new java.awt.Color(51, 102, 0));
        saveButton.setText("Save Changes");
        saveButton.addActionListener(this::saveButtonActionPerformed);
        optionPanel.add(saveButton);

        discardButton.setFont(GuiUtils.GOOGLE_SANS_16);
        discardButton.setForeground(new java.awt.Color(204, 0, 0));
        discardButton.setText("Discard Changes");
        discardButton.addActionListener(this::discardButtonActionPerformed);
        optionPanel.add(discardButton);

        signOutButton.setBackground(new java.awt.Color(255, 0, 0));
        signOutButton.setFont(GuiUtils.GOOGLE_SANS_16);
        signOutButton.setForeground(new java.awt.Color(255, 255, 255));
        signOutButton.setText("Sign Out");
        signOutButton.addActionListener(this::signOutButtonActionPerformed);
        optionPanel.add(signOutButton);

        permissionLabel.setFont(GuiUtils.GOOGLE_SANS_14);
        permissionLabel.setText("You logged in as an");

        backButton.setFont(GuiUtils.GOOGLE_SANS_16);
        backButton.setText("Back");
        backButton.addActionListener(this::backButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(permissionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(280, 280, 280)
                                .addComponent(middlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(backButton))
                        .addGap(17, 298, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(middlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(permissionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if (userLoginSession == null || userLoginSession.getUserId() == null) return;

        int userId = userLoginSession.getUserId();
        String username = usernameField.getText().trim();
        String password = new String(passwordField.getPassword()).trim();
        String fullName = fullNameField.getText().trim();
        String ageText = ageField.getText().trim();
        String phone = phoneField.getText().trim();
        String address = addressField.getText().trim();

        if (!AuthUtils.isValidUsername(username)) { DialogUtils.showDialogInvalidUsername(); return; }
        if (!password.isEmpty() && !AuthUtils.isValidPassword(password)) { DialogUtils.showDialogInvalidPWs(); return; }

        int age = 0;
        try { age = Integer.parseInt(ageText); } catch (Exception ex) { javax.swing.JOptionPane.showMessageDialog(this, "Age must be an integer.", "Validation", javax.swing.JOptionPane.WARNING_MESSAGE); return; }

        try {
            boolean ok = true;
            // username update returns 1 on success, 0 if exists, -1 if invalid
            int unameResult = userService.updateUsername(userId, username);
            if (unameResult == 0) { DialogUtils.showDialogUserAlreadyExists(username); return; }
            if (unameResult == -1) { DialogUtils.showDialogInvalidUsername(); return; }

            if (!password.isEmpty()) {
                ok = userService.updatePassword(userId, password);
            }

            if (ok) ok = userService.updateFullName(userId, fullName);
            if (ok) ok = userService.updateAge(userId, age);
            if (ok) ok = userService.updatePhoneNumber(userId, phone);
            if (ok) ok = userService.updateAddress(userId, address);

            if (ok) {
                // refresh session info from DB and update UI
                try { userLoginSession.reload(); } catch (Exception e) { /* ignore */ }
                updatePanel();
                javax.swing.JOptionPane.showMessageDialog(this, "Account updated successfully.", "Updated", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Account update failed.", "Failure", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "SQL Error: " + ex.getClass().getSimpleName() + ": " + ex.getMessage(), "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        passwordField.setText("");
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void userIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userIdFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void discardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discardButtonActionPerformed
        updatePanel();
    }//GEN-LAST:event_discardButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // System.out.println(appPanelSwitcher);
        if (appPanelSwitcher != null) {
            appPanelSwitcher.showPanel(AppPanel.MAIN);
        }
    }//GEN-LAST:event_backButtonActionPerformed

    private void signOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutButtonActionPerformed
        userLoginSession.clearSessionInfo();
        appPanelSwitcher.showPanel(AppPanel.AUTH);
    }//GEN-LAST:event_signOutButtonActionPerformed

    public void updatePanel() {
        if (userLoginSession == null) return;

        userIdField.setText(userLoginSession.getUserId().toString());
        usernameField.setText(userLoginSession.getUsername());
        fullNameField.setText(userLoginSession.getFullName());
        ageField.setText(userLoginSession.getAge().toString());
        phoneField.setText(userLoginSession.getPhoneNumber());
        addressField.setText(userLoginSession.getAddress());
        passwordField.setText("");

        permissionLabel.setText(USER_ROLE_PREFIX + ((userLoginSession.getUserRoleId() == 2) ? "Administrator.": "Passenger"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField ageField;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JButton discardButton;
    private javax.swing.JTextField fullNameField;
    private javax.swing.JLabel fullNameLabel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel middlePanel;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel permissionLabel;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton signOutButton;
    private javax.swing.JTextField userIdField;
    private javax.swing.JLabel userIdLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
