package com.buspass.gui.app_gui.dialogs;

import java.util.LinkedHashMap;
import javax.swing.JOptionPane;

import com.buspass.queries.BusQuery;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author USER
 */
public class BusUpdatePanel extends javax.swing.JPanel {

    /**
     * Creates new form UserCreatePanel
     */
    private final BusQuery busQuery;
    private LinkedHashMap<String,Object> currentBus; // cached fetched bus row

    public BusUpdatePanel(BusQuery busQuery) {
        initComponents();
        this.busQuery = busQuery != null ? busQuery : new BusQuery();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionPanel = new javax.swing.JPanel();
        updateButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        leftPanel = new javax.swing.JPanel();
        busIdLabel = new javax.swing.JLabel();
        plateNumberLabel = new javax.swing.JLabel();
        capacityLabel = new javax.swing.JLabel();
        driverIdLabel = new javax.swing.JLabel();
        routeIdLabel = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        busIdPanel = new javax.swing.JPanel();
        busIdField = new javax.swing.JTextField();
        findIdButton = new javax.swing.JButton();
        plateNumberField = new javax.swing.JTextField();
        capacityField = new javax.swing.JTextField();
        driverIdField = new javax.swing.JTextField();
        routeIdField = new javax.swing.JTextField();

        optionPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 5));

        updateButton.setFont(new java.awt.Font("Google Sans", 0, 16)); // NOI18N
        updateButton.setText("UPDATE");
        updateButton.addActionListener(this::updateButtonActionPerformed);
        optionPanel.add(updateButton);

        cancelButton.setFont(new java.awt.Font("Google Sans", 0, 16)); // NOI18N
        cancelButton.setText("CANCEL");
        optionPanel.add(cancelButton);

        headerPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        headerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("UPDATE BUS");
        headerPanel.add(headerLabel);

        leftPanel.setLayout(new java.awt.GridLayout(8, 1));

        busIdLabel.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        busIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        busIdLabel.setText("BusID");
        leftPanel.add(busIdLabel);

        plateNumberLabel.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        plateNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        plateNumberLabel.setText("Plate Number");
        leftPanel.add(plateNumberLabel);

        capacityLabel.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        capacityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        capacityLabel.setText("Capacity");
        leftPanel.add(capacityLabel);

        driverIdLabel.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        driverIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        driverIdLabel.setText("DriverID");
        leftPanel.add(driverIdLabel);

        routeIdLabel.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        routeIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        routeIdLabel.setText("RouteID");
        leftPanel.add(routeIdLabel);

        rightPanel.setLayout(new java.awt.GridLayout(8, 1));

        busIdField.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        busIdField.addActionListener(this::busIdFieldActionPerformed);

        findIdButton.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        findIdButton.setText("Find");
        findIdButton.addActionListener(this::findIdButtonActionPerformed);

        javax.swing.GroupLayout busIdPanelLayout = new javax.swing.GroupLayout(busIdPanel);
        busIdPanel.setLayout(busIdPanelLayout);
        busIdPanelLayout.setHorizontalGroup(
            busIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, busIdPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(busIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(findIdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        busIdPanelLayout.setVerticalGroup(
            busIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(findIdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(busIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        rightPanel.add(busIdPanel);

        plateNumberField.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        rightPanel.add(plateNumberField);

        capacityField.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        rightPanel.add(capacityField);

        driverIdField.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        rightPanel.add(driverIdField);

        routeIdField.setFont(new java.awt.Font("Google Sans", 0, 14)); // NOI18N
        rightPanel.add(routeIdField);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(optionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(headerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void busIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busIdFieldActionPerformed

    private void findIdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findIdButtonActionPerformed
        fetchBus();
    }//GEN-LAST:event_findIdButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        performUpdate();
    }//GEN-LAST:event_updateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField busIdField;
    private javax.swing.JLabel busIdLabel;
    private javax.swing.JPanel busIdPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField capacityField;
    private javax.swing.JLabel capacityLabel;
    private javax.swing.JTextField driverIdField;
    private javax.swing.JLabel driverIdLabel;
    private javax.swing.JButton findIdButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JTextField plateNumberField;
    private javax.swing.JLabel plateNumberLabel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JTextField routeIdField;
    private javax.swing.JLabel routeIdLabel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables

    // Expose buttons for external listeners (e.g., dialog wrapper)
    public javax.swing.JButton getUpdateButton() { return updateButton; }
    public javax.swing.JButton getCancelButton() { return cancelButton; }
    public javax.swing.JButton getFindBusButton() { return findIdButton; }

    // Field getters specific to Bus
    private int getBusId() { return parseInt(busIdField.getText().trim(), -1); }
    private String getPlateNumber() { return plateNumberField.getText().trim(); }
    private Integer getCapacity() { return parseIntNullable(capacityField.getText().trim()); } // Updated to use JTextField
    private Integer getDriverId() { return parseIntNullable(driverIdField.getText().trim()); }
    private Integer getRouteId() { return parseIntNullable(routeIdField.getText().trim()); }

    private int parseInt(String s, int fallback) { 
        try { 
            return Integer.parseInt(s); 
        } catch (Exception e) { 
            return fallback; 
        } 
    }

    private Integer parseIntNullable(String s) { 
        if (s==null||s.isEmpty()) return null; 
        try { 
            return Integer.parseInt(s); 
        } catch (Exception e) { 
            return null; 
        } 
    }

    private void setBusFields(LinkedHashMap<String,Object> bus) {
        plateNumberField.setText(asString(bus.get("PlateNumber")));
        capacityField.setText(asString(bus.get("Capacity")));
        driverIdField.setText(asString(bus.get("DriverID"), asString(bus.get("DriverID"))));
        routeIdField.setText(asString(bus.get("RouteID")));        
    }
    
    private String asString(Object o) { return o==null?"":o.toString(); }
    private String asString(Object primary, String alt) { return primary!=null?primary.toString(): (alt==null?"":alt); }

    private void fetchBus() {
        int busId = getBusId();
        if (busId <= 0) { 
            JOptionPane.showMessageDialog(this, "Enter a valid BusID.", "Input", JOptionPane.WARNING_MESSAGE); 
            return; 
        }
        currentBus = busQuery.getBusInfoById(busId);

        if (currentBus == null) { 
            JOptionPane.showMessageDialog(this, "Bus not found.", "Not Found", JOptionPane.INFORMATION_MESSAGE); 
            return; 
        }
        setBusFields(currentBus);
    }

    private void performUpdate() {
        int busId = getBusId();
        if (busId <= 0) { JOptionPane.showMessageDialog(this, "Provide BusID first.", "Validation", JOptionPane.WARNING_MESSAGE); return; }
        if (currentBus == null) currentBus = busQuery.getBusInfoById(busId);
        if (currentBus == null) { JOptionPane.showMessageDialog(this, "Fetch bus before updating.", "Validation", JOptionPane.WARNING_MESSAGE); return; }

        String newPlate = getPlateNumber();
        Integer newCapacity = getCapacity();
        Integer newDriverId = getDriverId();
        Integer newRouteId = getRouteId();

        StringBuilder summary = new StringBuilder();
        boolean anyChange = false;
        try {
            if (!newPlate.isEmpty() && !newPlate.equals(asString(currentBus.get("PlateNumber")))) {
                if (busQuery.updateBusPlate(busId, newPlate)) { summary.append("Plate updated.\n"); anyChange = true; }
            }
            if (newCapacity != null && !asString(currentBus.get("Capacity")).equals(String.valueOf(newCapacity))) {
                if (busQuery.updateCapacity(busId, newCapacity)) { summary.append("Capacity updated.\n"); anyChange = true; }
            }
            if (newDriverId != null && !asString(currentBus.get("DriverID"), asString(currentBus.get("DriverID"))).equals(String.valueOf(newDriverId))) {
                if (busQuery.updateDriverID(busId, newDriverId)) { summary.append("DriverID updated.\n"); anyChange = true; }
            }
            if (newRouteId != null && !asString(currentBus.get("RouteID")).equals(String.valueOf(newRouteId))) {
                if (busQuery.updateRouteID(busId, newRouteId)) { summary.append("RouteID updated.\n"); anyChange = true; }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Update failed: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (anyChange) {
            JOptionPane.showMessageDialog(this, summary.toString(), "Update Success", JOptionPane.INFORMATION_MESSAGE);
            currentBus = busQuery.getBusInfoById(busId); // refresh cache
            setBusFields(currentBus);
        } else {
            JOptionPane.showMessageDialog(this, "No changes applied.", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }
}
