package com.buspass.gui.app_gui.dialogs;

import java.util.LinkedHashMap;
import javax.swing.JOptionPane;

import com.buspass.queries.DriverQuery;
import com.buspass.utils.GuiUtils;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author USER
 */
public class DriverUpdatePanel extends javax.swing.JPanel {

    /**
     * Creates new form UserCreatePanel
     */
    private final DriverQuery driverQuery;
    private LinkedHashMap<String,Object> currentDriver; // cached fetched bus row

    public DriverUpdatePanel(DriverQuery driverQuery) {
        initComponents();
        this.driverQuery = driverQuery != null ? driverQuery : new DriverQuery();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionPanel = new javax.swing.JPanel();
        updateButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        leftPanel = new javax.swing.JPanel();
        driverIdLabel = new javax.swing.JLabel();
        driverNameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        licenseLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        driverIdPanel = new javax.swing.JPanel();
        driverIdField = new javax.swing.JTextField();
        findIdButton = new javax.swing.JButton();
        driverNameField = new javax.swing.JTextField();
        ageField = new javax.swing.JTextField();
        licenseField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();

        optionPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 5));

        updateButton.setFont(GuiUtils.GOOGLE_SANS_16);
        updateButton.setText("UPDATE");
        updateButton.addActionListener(this::updateButtonActionPerformed);
        optionPanel.add(updateButton);

        cancelButton.setFont(GuiUtils.GOOGLE_SANS_16);
        cancelButton.setText("CANCEL");
        optionPanel.add(cancelButton);

        headerPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        headerLabel.setFont(GuiUtils.LEXEND_MEDIUM_18);
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("UPDATE DRIVER");
        headerPanel.add(headerLabel);

        leftPanel.setLayout(new java.awt.GridLayout(6, 1));

        driverIdLabel.setFont(GuiUtils.GOOGLE_SANS_14);
        driverIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        driverIdLabel.setText("Driver ID");
        leftPanel.add(driverIdLabel);

        driverNameLabel.setFont(GuiUtils.GOOGLE_SANS_14);
        driverNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        driverNameLabel.setText("Driver Name");
        leftPanel.add(driverNameLabel);

        ageLabel.setFont(GuiUtils.GOOGLE_SANS_14);
        ageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ageLabel.setText("Age");
        leftPanel.add(ageLabel);

        licenseLabel.setFont(GuiUtils.GOOGLE_SANS_14);
        licenseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        licenseLabel.setText("License");
        leftPanel.add(licenseLabel);

        phoneLabel.setFont(GuiUtils.GOOGLE_SANS_14);
        phoneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        phoneLabel.setText("Phone Number");
        leftPanel.add(phoneLabel);

        rightPanel.setLayout(new java.awt.GridLayout(6, 1));

        driverIdField.setFont(GuiUtils.GOOGLE_SANS_14);
        driverIdField.addActionListener(this::driverIdFieldActionPerformed);

        findIdButton.setFont(GuiUtils.GOOGLE_SANS_14);
        findIdButton.setText("Find");
        findIdButton.addActionListener(this::findIdButtonActionPerformed);

        javax.swing.GroupLayout driverIdPanelLayout = new javax.swing.GroupLayout(driverIdPanel);
        driverIdPanel.setLayout(driverIdPanelLayout);
        driverIdPanelLayout.setHorizontalGroup(
            driverIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, driverIdPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(driverIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(findIdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        driverIdPanelLayout.setVerticalGroup(
            driverIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(driverIdField)
            .addComponent(findIdButton, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        rightPanel.add(driverIdPanel);

        driverNameField.setFont(GuiUtils.GOOGLE_SANS_14);
        rightPanel.add(driverNameField);

        ageField.setFont(GuiUtils.GOOGLE_SANS_14);
        rightPanel.add(ageField);

        licenseField.setFont(GuiUtils.GOOGLE_SANS_14);
        rightPanel.add(licenseField);

        phoneField.setFont(GuiUtils.GOOGLE_SANS_14);
        rightPanel.add(phoneField);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(optionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(headerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void driverIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driverIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_driverIdFieldActionPerformed

    private void findIdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findIdButtonActionPerformed
        fetchDriver();
    }//GEN-LAST:event_findIdButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        performUpdate();
    }//GEN-LAST:event_updateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageField;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField driverIdField;
    private javax.swing.JLabel driverIdLabel;
    private javax.swing.JPanel driverIdPanel;
    private javax.swing.JTextField driverNameField;
    private javax.swing.JLabel driverNameLabel;
    private javax.swing.JButton findIdButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JTextField licenseField;
    private javax.swing.JLabel licenseLabel;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables

    // Expose buttons for external listeners (e.g., dialog wrapper)
    public javax.swing.JButton getUpdateButton() { return updateButton; }
    public javax.swing.JButton getCancelButton() { return cancelButton; }
    public javax.swing.JButton getFindBusButton() { return findIdButton; }

    // Field getters specific to Bus
    private int getDriverId() { return parseInt(driverIdField.getText().trim(), -1); }
    private String getDriverName() { return driverNameField.getText().trim(); }
    private Integer getAge() { return parseIntNullable(ageField.getText().trim()); } // Updated to use JTextField
    private String getLicense() { return licenseField.getText().trim(); }
    private String getPhoneNumber() { return phoneField.getText().trim(); }

    private int parseInt(String s, int fallback) { 
        try { 
            return Integer.parseInt(s); 
        } catch (Exception e) { 
            return fallback; 
        } 
    }

    private Integer parseIntNullable(String s) { 
        if (s==null||s.isEmpty()) return null; 
        try { 
            return Integer.parseInt(s); 
        } catch (Exception e) { 
            return null; 
        } 
    }

    private void setDriverFields(LinkedHashMap<String,Object> driver) {
        driverNameField.setText(asString(driver.get("DriverName")));
        ageField.setText(asString(driver.get("Age")));
        licenseField.setText(asString(driver.get(""), asString(driver.get("License"))));
        phoneField.setText(asString(driver.get("Phone")));        
    }

    private String asString(Object o) { return o==null?"":o.toString(); }
    private String asString(Object primary, String alt) { return primary!=null?primary.toString(): (alt==null?"":alt); }

    private void fetchDriver() {
        int driverId = getDriverId();
        if (driverId <= 0) { 
            JOptionPane.showMessageDialog(this, "Enter a valid DriverID.", "Input", JOptionPane.WARNING_MESSAGE); 
            return; 
        }
        currentDriver = driverQuery.getDriverById(driverId);

        if (currentDriver == null) { 
            JOptionPane.showMessageDialog(this, "Driver not found.", "Not Found", JOptionPane.INFORMATION_MESSAGE); 
            return; 
        }
        setDriverFields(currentDriver);
    }

    private void performUpdate() {
        int driverId = getDriverId();
        if (driverId <= 0) { JOptionPane.showMessageDialog(this, "Provide DriverID first.", "Validation", JOptionPane.WARNING_MESSAGE); return; }
        if (currentDriver == null) currentDriver = driverQuery.getDriverById(driverId);
        if (currentDriver == null) { JOptionPane.showMessageDialog(this, "Fetch driver before updating.", "Validation", JOptionPane.WARNING_MESSAGE); return; }

        String newDriverName = getDriverName();
        Integer newAge = getAge();
        String newLicense = getLicense();
        String newPhoneNumber = getPhoneNumber();

        StringBuilder summary = new StringBuilder();
        boolean anyChange = false;
        try {
            if (!newDriverName.isEmpty() && !newDriverName.equals(asString(currentDriver.get("DriverName")))) {
                if (driverQuery.updateName(driverId, newDriverName)) { 
                    summary.append("Driver Name updated.\n"); 
                    anyChange = true; 
                }
            }
            if (newAge != null && !asString(currentDriver.get("Age")).equals(String.valueOf(newAge))) {
                if (driverQuery.updateAge(driverId, newAge)) { 
                    summary.append("Age updated.\n"); 
                    anyChange = true; 
                }
            }
            if (newLicense != null && !asString(currentDriver.get("License"), asString(currentDriver.get(""))).equals(String.valueOf(newLicense))) {
                if (driverQuery.updateLicense(driverId, newLicense)) { 
                    summary.append("DriverID updated.\n"); 
                    anyChange = true; 
                }
            }
            if (newPhoneNumber != null && !asString(currentDriver.get("Phone")).equals(String.valueOf(newPhoneNumber))) {
                if (driverQuery.updatePhoneNumber(driverId, newPhoneNumber)) { 
                    summary.append("RouteID updated.\n"); 
                    anyChange = true; 
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Update failed: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (anyChange) {
            JOptionPane.showMessageDialog(this, summary.toString(), "Update Success", JOptionPane.INFORMATION_MESSAGE);
            currentDriver = driverQuery.getDriverById(driverId); // refresh cache
            setDriverFields(currentDriver);
        } else {
            JOptionPane.showMessageDialog(this, "No changes applied.", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }
}
