package com.buspass.gui.app_gui.dialogs;

import java.util.Map;
import javax.swing.JOptionPane;

import com.buspass.queries.DriverQuery;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author USER
 */
public class DriverCreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form UserCreatePanel
     */
    private final DriverQuery driverQuery;

    public DriverCreatePanel(DriverQuery driverQuery) {
        initComponents();
        this.driverQuery = driverQuery != null ? driverQuery : new DriverQuery();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionPanel = new javax.swing.JPanel();
        createButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        leftPanel = new javax.swing.JPanel();
        driverNameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        licenseLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        driverNameField = new javax.swing.JTextField();
        ageField = new javax.swing.JTextField();
        licenseField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();

        optionPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 5));

        createButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        createButton.setText("CREATE");
        createButton.addActionListener(this::createButtonActionPerformed);
        optionPanel.add(createButton);

        cancelButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cancelButton.setText("CANCEL");
        optionPanel.add(cancelButton);

        headerPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        headerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("CREATE DRIVER");
        headerPanel.add(headerLabel);

        leftPanel.setLayout(new java.awt.GridLayout(6, 1));

        driverNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        driverNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        driverNameLabel.setText("Driver Name");
        leftPanel.add(driverNameLabel);

        ageLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ageLabel.setText("Age");
        leftPanel.add(ageLabel);

        licenseLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        licenseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        licenseLabel.setText("License");
        leftPanel.add(licenseLabel);

        phoneLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        phoneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        phoneLabel.setText("Phone Number");
        leftPanel.add(phoneLabel);

        rightPanel.setLayout(new java.awt.GridLayout(6, 1));

        driverNameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rightPanel.add(driverNameField);

        ageField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rightPanel.add(ageField);

        licenseField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rightPanel.add(licenseField);

        phoneField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rightPanel.add(phoneField);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(optionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(headerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        performInsert();
    }//GEN-LAST:event_createButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageField;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createButton;
    private javax.swing.JTextField driverNameField;
    private javax.swing.JLabel driverNameLabel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JTextField licenseField;
    private javax.swing.JLabel licenseLabel;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JPanel rightPanel;
    // End of variables declaration//GEN-END:variables

    // Expose buttons for external listeners (e.g., dialog wrapper)
    public javax.swing.JButton getCreateButton() { return createButton; }
    public javax.swing.JButton getCancelButton() { return cancelButton; }

    // Field getters specific to Bus
    private String getDriverName() { return driverNameField.getText().trim(); }
    private Integer getAge() { return parseIntNullable(ageField.getText().trim()); } // Updated to use JTextField
    private String getLicense() { return licenseField.getText().trim(); }
    private String getPhoneNumber() { return phoneField.getText().trim(); }

    private Integer parseIntNullable(String s) { 
        if (s==null||s.isEmpty()) return null; 
        try { 
            return Integer.parseInt(s); 
        } catch (Exception e) { 
            return null; 
        } 
    }

    private void performInsert() {

        String driverName = getDriverName();
        Integer age = getAge();
        String license = getLicense();
        String phoneNumber = getPhoneNumber();

        boolean ok;
        try {
            ok = driverQuery.registerDriver(driverName, age, license, phoneNumber);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Record Creation failed: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!ok) 
            JOptionPane.showMessageDialog(this, "Record Creation failed.", "Error", JOptionPane.ERROR_MESSAGE);
        else
            JOptionPane.showMessageDialog(this, "New Driver Record Created.", "Info", JOptionPane.INFORMATION_MESSAGE);
    }
}
