package com.buspass.gui.app_gui.dialogs;

import java.util.LinkedHashMap;

import javax.swing.JButton;

import com.buspass.queries.TripQuery;
import com.buspass.utils.GuiUtils;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author USER
 */
public class PurchaseTicketPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserCreatePanel
     */
    TripQuery tripQuery;

    public PurchaseTicketPanel(TripQuery tripQuery) {
        initComponents();
        this.tripQuery = tripQuery;
        // Gray out (disable) input fields so they appear read-only
        setFieldsEditable(false);
    }

    public JButton getPurchaseButton() { return purchaseButton; }
    public JButton getCancelButton() { return cancelButton; }

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionPanel = new javax.swing.JPanel();
        purchaseButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        leftPanel = new javax.swing.JPanel();
        tripIdLabel = new javax.swing.JLabel();
        routeNameLabel = new javax.swing.JLabel();
        tripDateLabel = new javax.swing.JLabel();
        departureTimeLabel = new javax.swing.JLabel();
        arrivalTimeLabel = new javax.swing.JLabel();
        startLocationLabel = new javax.swing.JLabel();
        endLocationLabel = new javax.swing.JLabel();
        capacityLabel = new javax.swing.JLabel();
        durationLabel = new javax.swing.JLabel();
        busPlateNumberLabel = new javax.swing.JLabel();
        fareLabel = new javax.swing.JLabel();
        paymentMethodLabel = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        tripIdField = new javax.swing.JTextField();
        routeNameField = new javax.swing.JTextField();
        tripDateField = new javax.swing.JTextField();
        departureTimeField = new javax.swing.JTextField();
        arrivalTimeField = new javax.swing.JTextField();
        startLocationField = new javax.swing.JTextField();
        endLocationField = new javax.swing.JTextField();
        capacityField = new javax.swing.JTextField();
        durationField = new javax.swing.JTextField();
        busPlateNumberField = new javax.swing.JTextField();
        fareField = new javax.swing.JTextField();
        paymentMethodComboBox = new javax.swing.JComboBox<>();

        optionPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 5));

        purchaseButton.setFont(GuiUtils.GOOGLE_SANS_16); // NOI18N
        purchaseButton.setText("PURCHASE");
        purchaseButton.addActionListener(this::purchaseButtonActionPerformed);
        optionPanel.add(purchaseButton);

        cancelButton.setFont(GuiUtils.GOOGLE_SANS_16); // NOI18N
        cancelButton.setText("CANCEL");
        optionPanel.add(cancelButton);

        headerPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        headerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("PURCHASE TICKET FOR TRIP");
        headerPanel.add(headerLabel);

        leftPanel.setLayout(new java.awt.GridLayout(13, 1));

        tripIdLabel.setFont(GuiUtils.GOOGLE_SANS_14); // NOI18N
        tripIdLabel.setForeground(new java.awt.Color(0, 102, 102));
        tripIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tripIdLabel.setText("Trip ID");
        leftPanel.add(tripIdLabel);

        routeNameLabel.setFont(GuiUtils.GOOGLE_SANS_14); // NOI18N
        routeNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        routeNameLabel.setText("Route Name");
        leftPanel.add(routeNameLabel);

        tripDateLabel.setFont(GuiUtils.GOOGLE_SANS_14); // NOI18N
        tripDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tripDateLabel.setText("Trip Date");
        leftPanel.add(tripDateLabel);

        departureTimeLabel.setFont(GuiUtils.GOOGLE_SANS_14); // NOI18N
        departureTimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        departureTimeLabel.setText("Departure Time");
        leftPanel.add(departureTimeLabel);

        arrivalTimeLabel.setFont(GuiUtils.GOOGLE_SANS_14); // NOI18N
        arrivalTimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arrivalTimeLabel.setText("Arrival Time");
        leftPanel.add(arrivalTimeLabel);

        startLocationLabel.setFont(GuiUtils.GOOGLE_SANS_14); // NOI18N
        startLocationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        startLocationLabel.setText("Start Location");
        leftPanel.add(startLocationLabel);

        endLocationLabel.setFont(GuiUtils.GOOGLE_SANS_14); // NOI18N
        endLocationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        endLocationLabel.setText("End Location");
        leftPanel.add(endLocationLabel);

        capacityLabel.setFont(GuiUtils.GOOGLE_SANS_14); // NOI18N
        capacityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        capacityLabel.setText("Capacity");
        leftPanel.add(capacityLabel);

        durationLabel.setFont(GuiUtils.GOOGLE_SANS_14); // NOI18N
        durationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        durationLabel.setText("Duration");
        leftPanel.add(durationLabel);

        busPlateNumberLabel.setFont(GuiUtils.GOOGLE_SANS_14); // NOI18N
        busPlateNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        busPlateNumberLabel.setText("Bus Plate Number");
        leftPanel.add(busPlateNumberLabel);

        fareLabel.setFont(GuiUtils.GOOGLE_SANS_14); // NOI18N
        fareLabel.setForeground(new java.awt.Color(153, 0, 153));
        fareLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fareLabel.setText("Fare");
        leftPanel.add(fareLabel);

        paymentMethodLabel.setFont(GuiUtils.GOOGLE_SANS_14); // NOI18N
        paymentMethodLabel.setForeground(new java.awt.Color(153, 0, 153));
        paymentMethodLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paymentMethodLabel.setText("Payment Method");
        leftPanel.add(paymentMethodLabel);

        rightPanel.setLayout(new java.awt.GridLayout(13, 1));

        tripIdField.setFont(GuiUtils.GOOGLE_SANS_14); // NOI18N
        tripIdField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        rightPanel.add(tripIdField);

        routeNameField.setFont(GuiUtils.GOOGLE_SANS_14); // NOI18N
        routeNameField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        rightPanel.add(routeNameField);

        tripDateField.setFont(GuiUtils.GOOGLE_SANS_14); // NOI18N
        tripDateField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        rightPanel.add(tripDateField);

        departureTimeField.setFont(GuiUtils.GOOGLE_SANS_14); // NOI18N
        departureTimeField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        rightPanel.add(departureTimeField);

        arrivalTimeField.setFont(GuiUtils.GOOGLE_SANS_14); // NOI18N
        arrivalTimeField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        rightPanel.add(arrivalTimeField);

        startLocationField.setFont(GuiUtils.GOOGLE_SANS_14); // NOI18N
        startLocationField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        rightPanel.add(startLocationField);

        endLocationField.setFont(GuiUtils.GOOGLE_SANS_14); // NOI18N
        endLocationField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        rightPanel.add(endLocationField);

        capacityField.setFont(GuiUtils.GOOGLE_SANS_14); // NOI18N
        capacityField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        rightPanel.add(capacityField);

        durationField.setFont(GuiUtils.GOOGLE_SANS_14); // NOI18N
        durationField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        rightPanel.add(durationField);

        busPlateNumberField.setFont(GuiUtils.GOOGLE_SANS_14); // NOI18N
        busPlateNumberField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        rightPanel.add(busPlateNumberField);

        fareField.setFont(GuiUtils.GOOGLE_SANS_14); // NOI18N
        fareField.setDisabledTextColor(new java.awt.Color(102, 0, 153));
        rightPanel.add(fareField);

        paymentMethodComboBox.setFont(GuiUtils.GOOGLE_SANS_14); // NOI18N
        paymentMethodComboBox.setForeground(new java.awt.Color(102, 0, 102));
        paymentMethodComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Chosen", "Card", "Online Banking" }));
        paymentMethodComboBox.addActionListener(this::paymentMethodComboBoxActionPerformed);
        rightPanel.add(paymentMethodComboBox);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(optionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(headerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                    .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void purchaseButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_updateButtonActionPerformed

    }// GEN-LAST:event_updateButtonActionPerformed

    private void paymentMethodComboBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_paymentMethodComboBoxActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_paymentMethodComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arrivalTimeField;
    private javax.swing.JLabel arrivalTimeLabel;
    private javax.swing.JTextField busPlateNumberField;
    private javax.swing.JLabel busPlateNumberLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField capacityField;
    private javax.swing.JLabel capacityLabel;
    private javax.swing.JTextField departureTimeField;
    private javax.swing.JLabel departureTimeLabel;
    private javax.swing.JTextField durationField;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JTextField endLocationField;
    private javax.swing.JLabel endLocationLabel;
    private javax.swing.JTextField fareField;
    private javax.swing.JLabel fareLabel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JComboBox<String> paymentMethodComboBox;
    private javax.swing.JLabel paymentMethodLabel;
    private javax.swing.JButton purchaseButton;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JTextField routeNameField;
    private javax.swing.JLabel routeNameLabel;
    private javax.swing.JTextField startLocationField;
    private javax.swing.JLabel startLocationLabel;
    private javax.swing.JTextField tripDateField;
    private javax.swing.JLabel tripDateLabel;
    private javax.swing.JTextField tripIdField;
    private javax.swing.JLabel tripIdLabel;
    // End of variables declaration//GEN-END:variables

    // Expose buttons for external listeners (e.g., dialog wrapper)
    public javax.swing.JButton getUpdateButton() {
        return purchaseButton;
    }
    // Text getters for purchase ticket fields
    private String getTripId() { return tripIdField.getText().trim(); }
    private String getRouteName() { return routeNameField.getText().trim(); }
    private String getTripDate() { return tripDateField.getText().trim(); }
    private String getDepartureTime() { return departureTimeField.getText().trim(); }
    private String getArrivalTime() { return arrivalTimeField.getText().trim(); }
    private String getStartLocation() { return startLocationField.getText().trim(); }
    private String getEndLocation() { return endLocationField.getText().trim(); }
    private String getBusPlateNumber() { return busPlateNumberField.getText().trim(); }
    private String getFare() { return fareField.getText().trim(); }
    public int getPaymentMethod() {
        return paymentMethodComboBox.getSelectedIndex();
    }
    

    // Public setters for form fields (allow external code to populate values)
    public void setTripId(String tripId) {
        tripIdField.setText(tripId == null ? "" : tripId);
    }

    public void setRouteName(String routeName) {
        routeNameField.setText(routeName == null ? "" : routeName);
    }

    public void setTripDate(String tripDate) {
        tripDateField.setText(tripDate == null ? "" : tripDate);
    }

    public void setDepartureTime(String departureTime) {
        departureTimeField.setText(departureTime == null ? "" : departureTime);
    }

    public void setArrivalTime(String arrivalTime) {
        arrivalTimeField.setText(arrivalTime == null ? "" : arrivalTime);
    }

    public void setStartLocation(String startLocation) {
        startLocationField.setText(startLocation == null ? "" : startLocation);
    }

    public void setEndLocation(String endLocation) {
        endLocationField.setText(endLocation == null ? "" : endLocation);
    }

    public void setCapacity(String capacity) {
        capacityField.setText(capacity == null ? "" : capacity);
    }

    public void setDuration(String duration) {
        durationField.setText(duration == null ? "" : duration);
    }

    public void setBusPlateNumber(String plate) {
        busPlateNumberField.setText(plate == null ? "" : plate);
    }

    public void setFare(String fare) {
        fareField.setText(fare == null ? "0" : fare + " VND");
    }

    public void setPaymentMethod(String method) {
        if (method == null) {
            paymentMethodComboBox.setSelectedIndex(0);
            return;
        }
        for (int i = 0; i < paymentMethodComboBox.getItemCount(); i++) {
            if (method.equalsIgnoreCase(paymentMethodComboBox.getItemAt(i))) {
                paymentMethodComboBox.setSelectedIndex(i);
                return;
            }
        }
        // fallback: add and select
        paymentMethodComboBox.addItem(method);
        paymentMethodComboBox.setSelectedItem(method);
    }

    // Helper to enable/disable (gray out) all input fields
    public void setFieldsEditable(boolean editable) {
        tripIdField.setEnabled(editable);
        routeNameField.setEnabled(editable);
        tripDateField.setEnabled(editable);
        departureTimeField.setEnabled(editable);
        arrivalTimeField.setEnabled(editable);
        startLocationField.setEnabled(editable);
        endLocationField.setEnabled(editable);
        capacityField.setEnabled(editable);
        durationField.setEnabled(editable);
        busPlateNumberField.setEnabled(editable);
        fareField.setEnabled(editable);
    }

    public void setFields(int tripId) {
        LinkedHashMap<String, Object> trip = tripQuery.getTripDetailedById(tripId);

        setRouteName(trip.get("RouteName").toString());
        setTripDate(trip.get("TripDate").toString());
        setDepartureTime(trip.get("DepartureTime").toString());
        setArrivalTime(trip.get("ArrivalTime").toString());
        setStartLocation(trip.get("StartLocation").toString());
        setEndLocation(trip.get("EndLocation").toString());
        setCapacity(trip.get("Capacity").toString());
        setDuration(trip.get("Duration").toString());
        setBusPlateNumber(trip.get("PlateNumber").toString());
        setFare(trip.get("Fare").toString());
    }
}
