package com.buspass.gui.app_gui.dialogs;

import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Map;

import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.DateFormatter;
import javax.swing.text.NumberFormatter;

import com.buspass.queries.TripQuery;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author USER
 */
public class TripFilterPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserCreatePanel
     */
    private final TripQuery tripQuery;

    public TripFilterPanel(TripQuery tripQuery) {
        numberFormatter.setAllowsInvalid(false); // Disallow invalid edits
        numberFormatter.setCommitsOnValidEdit(true);

        initComponents();
        this.tripQuery = tripQuery != null ? tripQuery : new TripQuery();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionPanel = new javax.swing.JPanel();
        filterButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        leftPanel = new javax.swing.JPanel();
        tripDateLabel = new javax.swing.JLabel();
        routeNamesLabel = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        tripDateField = new javax.swing.JFormattedTextField(df);
        routeNamesField = new javax.swing.JFormattedTextField(numberFormatter);

        optionPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 5));

        filterButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        filterButton.setText("FILTER");
        filterButton.addActionListener(this::filterButtonActionPerformed);
        optionPanel.add(filterButton);

        cancelButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cancelButton.setText("CANCEL");
        optionPanel.add(cancelButton);

        headerPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        headerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("FILTER UPCOMING TRIP");
        headerPanel.add(headerLabel);

        leftPanel.setLayout(new java.awt.GridLayout(3, 1));

        tripDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tripDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tripDateLabel.setText("Trip Date");
        leftPanel.add(tripDateLabel);

        routeNamesLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        routeNamesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        routeNamesLabel.setText("Route Names");
        leftPanel.add(routeNamesLabel);

        rightPanel.setLayout(new java.awt.GridLayout(3, 1));

        tripDateField.addActionListener(this::tripDateFieldActionPerformed);
        rightPanel.add(tripDateField);

        routeNamesField.addActionListener(this::routeNamesFieldActionPerformed);
        rightPanel.add(routeNamesField);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(optionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(headerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void filterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterButtonActionPerformed
        getFilteredTrips();
    }//GEN-LAST:event_filterButtonActionPerformed

    private void tripDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tripDateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tripDateFieldActionPerformed

    private void routeNamesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routeNamesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_routeNamesFieldActionPerformed

    SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
    SimpleDateFormat tf = new SimpleDateFormat("HH:mm:ss");
    // Create a formatter that only allows integers
    NumberFormat integerFormat = NumberFormat.getIntegerInstance();
    NumberFormatter numberFormatter = new NumberFormatter(integerFormat);

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton filterButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JFormattedTextField routeNamesField;
    private javax.swing.JLabel routeNamesLabel;
    private javax.swing.JFormattedTextField tripDateField;
    private javax.swing.JLabel tripDateLabel;
    // End of variables declaration//GEN-END:variables

    // Expose buttons for external listeners (e.g., dialog wrapper)
    public javax.swing.JButton getFilterButton() { return filterButton; }
    public javax.swing.JButton getCancelButton() { return cancelButton; }

    // Field getters specific to Bus
    private String getTripDate() { return tripDateField.getText().trim(); }
    private String getRouteNames() { return routeNamesField.getText().trim(); }

    public List<Map<String, Object>> getFilteredTrips() {

        String tripDate = getTripDate();
        String routeNames = getRouteNames();

        List<Map<String, Object>> trips;
        try {
            if (tripDate.isBlank())
                trips = tripQuery.getFilteredRoutesTrips(routeNames);
            else if (routeNames.isBlank())
                trips = tripQuery.getFilteredDateTrips(tripDate);
            else 
                trips = tripQuery.getUpcomingTrips();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Trips Retrieval failed: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        return trips;
    }
}
