package com.buspass.gui.app_gui.dialogs;

import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.LinkedHashMap;
import java.util.regex.Pattern;
import java.awt.Color;

import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.DateFormatter;
import javax.swing.text.NumberFormatter;

import com.buspass.queries.TripQuery;
import com.buspass.utils.GuiUtils;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author USER
 */
public class TripFilterPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserCreatePanel
     */
    private final TripQuery tripQuery;

    public TripFilterPanel(TripQuery tripQuery) {
        initComponents();
        this.tripQuery = tripQuery != null ? tripQuery : new TripQuery();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionPanel = new javax.swing.JPanel();
        filterButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        leftPanel = new javax.swing.JPanel();
        fromDateLabel = new javax.swing.JLabel();
        routeNamesLabel = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        fromDateField = new javax.swing.JFormattedTextField(df);
        routeNamesField = new javax.swing.JFormattedTextField();

        optionPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 5));

        filterButton.setFont(GuiUtils.GOOGLE_SANS_16); // NOI18N
        filterButton.setText("FILTER");
        filterButton.addActionListener(this::filterButtonActionPerformed);
        optionPanel.add(filterButton);

        cancelButton.setFont(GuiUtils.GOOGLE_SANS_16); // NOI18N
        cancelButton.setText("CANCEL");
        optionPanel.add(cancelButton);

        headerPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        headerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("FILTER UPCOMING TRIP");
        headerPanel.add(headerLabel);

        leftPanel.setLayout(new java.awt.GridLayout(3, 1));

        fromDateLabel.setFont(GuiUtils.GOOGLE_SANS_14); // NOI18N
        fromDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fromDateLabel.setText("From Date");
        leftPanel.add(fromDateLabel);

        routeNamesLabel.setFont(GuiUtils.GOOGLE_SANS_14); // NOI18N
        routeNamesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        routeNamesLabel.setText("Route Names");
        leftPanel.add(routeNamesLabel);

        rightPanel.setLayout(new java.awt.GridLayout(3, 1));

        fromDateField.setFont(GuiUtils.GOOGLE_SANS_14); // NOI18N
        fromDateField.addActionListener(this::fromDateFieldActionPerformed);
        rightPanel.add(fromDateField);

        routeNamesField.setFont(GuiUtils.GOOGLE_SANS_14); // NOI18N
        routeNamesField.addActionListener(this::routeNamesFieldActionPerformed);
        rightPanel.add(routeNamesField);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(optionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(headerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void filterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterButtonActionPerformed
        getFilteredTrips();
    }//GEN-LAST:event_filterButtonActionPerformed

    private void fromDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromDateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromDateFieldActionPerformed

    private void routeNamesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routeNamesFieldActionPerformed
        String text = routeNamesField.getText();
        if (text == null) text = "";
        text = text.trim();
        if (!text.isEmpty() && !routeNamesPattern.matcher(text).matches()) {
            JOptionPane.showMessageDialog(this,
                    "Invalid route names format. Use numbers or ranges separated by commas, e.g. \"8, 10-12\".",
                    "Invalid input",
                    JOptionPane.WARNING_MESSAGE);
            routeNamesField.requestFocusInWindow();
            return;
        }
        // trigger filter when Enter pressed in the field
        getFilteredTrips();
    }//GEN-LAST:event_routeNamesFieldActionPerformed

    SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
    String routeNamesFormatter = "^\\s*[0-9]+(-[0-9]+)?(\\s*,\\s*[0-9]+(-[0-9]+)?)*\\s*$";
    Pattern routeNamesPattern = Pattern.compile(routeNamesFormatter);


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton filterButton;
    private javax.swing.JFormattedTextField fromDateField;
    private javax.swing.JLabel fromDateLabel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JFormattedTextField routeNamesField;
    private javax.swing.JLabel routeNamesLabel;
    // End of variables declaration//GEN-END:variables

    // Expose buttons for external listeners (e.g., dialog wrapper)
    public javax.swing.JButton getFilterButton() { return filterButton; }
    public javax.swing.JButton getCancelButton() { return cancelButton; }

    // Field getters specific to Bus
    public String getFromDate() { return fromDateField.getText().trim(); }
    public String getRouteNames() { return routeNamesField.getText().trim(); }

    public void setFromDate(String date) { fromDateField.setText(date); }
    public void setRouteNames(String routeNames) { routeNamesField.setText(routeNames); }

    public List<LinkedHashMap<String, Object>> getFilteredTrips() {

        String tripDate = getFromDate();
        String routeNames = getRouteNames();

        // validate routeNames before querying
        if (!routeNames.isBlank() && !routeNamesPattern.matcher(routeNames).matches()) {
            JOptionPane.showMessageDialog(this,
                    "Invalid route names format. Use numbers or ranges separated by commas, e.g. \"8, 10-12\".",
                    "Invalid input",
                    JOptionPane.WARNING_MESSAGE);
            return null;
        }

        // System.out.println(routeNames);


        List<LinkedHashMap<String, Object>> trips;
        try {
            if (tripDate.isBlank() && routeNames.isBlank())
                trips = tripQuery.getUpcomingTrips();
            else if (tripDate.isBlank())
                trips = tripQuery.getFilteredRoutesTrips(routeNames);
            else if (routeNames.isBlank())
                trips = tripQuery.getFilteredDateTrips(tripDate);
            else
                trips = tripQuery.getFilteredTrips(tripDate, routeNames);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Trips Retrieval failed: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        return trips;
    }
}
