package com.buspass.gui.app_gui.dialogs;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author USER
 */
public class UserUpdatePanel extends javax.swing.JPanel {

    /**
     * Creates new form UserCreatePanel
     */
    public UserUpdatePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionPanel = new javax.swing.JPanel();
        createButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        leftPanel = new javax.swing.JPanel();
        userIdLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        fullNameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        userRoleIdLabel = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        UserIdPanel = new javax.swing.JPanel();
        userIdField = new javax.swing.JTextField();
        findIdButton = new javax.swing.JButton();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        fullNameField = new javax.swing.JTextField();
        ageField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        userRoleIdField = new javax.swing.JTextField();

        optionPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 5));

        createButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        createButton.setText("CREATE");
        optionPanel.add(createButton);

        cancelButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cancelButton.setText("CANCEL");
        optionPanel.add(cancelButton);

        headerPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        headerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("UPDATE USER");
        headerPanel.add(headerLabel);

        leftPanel.setLayout(new java.awt.GridLayout(8, 1));

        userIdLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userIdLabel.setText("UserID");
        leftPanel.add(userIdLabel);

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameLabel.setText("Username");
        leftPanel.add(usernameLabel);

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordLabel.setText("Password");
        leftPanel.add(passwordLabel);

        fullNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fullNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fullNameLabel.setText("Full Name");
        leftPanel.add(fullNameLabel);

        ageLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ageLabel.setText("Age");
        leftPanel.add(ageLabel);

        phoneLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        phoneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        phoneLabel.setText("Phone Number");
        leftPanel.add(phoneLabel);

        addressLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addressLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addressLabel.setText("Address");
        leftPanel.add(addressLabel);

        userRoleIdLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userRoleIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userRoleIdLabel.setText("UserRoleID");
        leftPanel.add(userRoleIdLabel);

        rightPanel.setLayout(new java.awt.GridLayout(8, 1));

        userIdField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userIdField.addActionListener(this::userIdFieldActionPerformed);

        findIdButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        findIdButton.setText("Find");

        javax.swing.GroupLayout UserIdPanelLayout = new javax.swing.GroupLayout(UserIdPanel);
        UserIdPanel.setLayout(UserIdPanelLayout);
        UserIdPanelLayout.setHorizontalGroup(
            UserIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserIdPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(userIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(findIdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        UserIdPanelLayout.setVerticalGroup(
            UserIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserIdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(findIdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(userIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        rightPanel.add(UserIdPanel);

        usernameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rightPanel.add(usernameField);

        passwordField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordField.addActionListener(this::passwordFieldActionPerformed);
        rightPanel.add(passwordField);

        fullNameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rightPanel.add(fullNameField);

        ageField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rightPanel.add(ageField);

        phoneField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rightPanel.add(phoneField);

        addressField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rightPanel.add(addressField);

        userRoleIdField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rightPanel.add(userRoleIdField);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(optionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(headerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void userIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userIdFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UserIdPanel;
    private javax.swing.JTextField addressField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField ageField;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createButton;
    private javax.swing.JButton findIdButton;
    private javax.swing.JTextField fullNameField;
    private javax.swing.JLabel fullNameLabel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JTextField userIdField;
    private javax.swing.JLabel userIdLabel;
    private javax.swing.JTextField userRoleIdField;
    private javax.swing.JLabel userRoleIdLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables

    // Expose buttons for external listeners (e.g., dialog wrapper)
    public javax.swing.JButton getCreateButton() { return createButton; }
    public javax.swing.JButton getCancelButton() { return cancelButton; }

    // Text getters for form fields
    public String getUsername() { return usernameField.getText().trim(); }
    public String getPassword() { return new String(passwordField.getPassword()); }
    public String getFullName() { return fullNameField.getText().trim(); }
    public Integer getAge() { return Integer.parseInt(ageField.getText().trim()); }
    public String getPhone() { return phoneField.getText().trim(); }
    public String getAddress() { return addressField.getText().trim(); }
    public Integer getUserRoleId() { return Integer.parseInt(userRoleIdField.getText().trim()); }
}
