-- Create
-- Note: PaymentID is AUTO_INCREMENT and will be generated by the DB
INSERT INTO Payment (UserID, Amount, PaymentDate, Payment_Method_ID)
VALUES (?, ?, ?, ?);

-- Read
SELECT * FROM Payment;

-- Read + JOIN (User + Payment Method)
SELECT p.Amount,
       p.PaymentDate AS TransactionTime,
       u.Username,
       pm.Method AS PaymentMethod
FROM Payment p
    LEFT JOIN `User` u ON p.UserID = u.UserID
    LEFT JOIN Payment_Methods pm ON p.Payment_Method_ID = pm.Payment_Method_ID;

-- Update
UPDATE Payment
SET UserID = ?, Amount = ?, PaymentDate = ?, Payment_Method_ID = ?
WHERE PaymentID = ?;

-- Delete
DELETE FROM Payment WHERE PaymentID = ?;

