/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.buspass.gui.app_gui.admin;

import com.buspass.queries.DriverQuery;

/**
 *
 * @author USER
 */
public class DriversPanel extends javax.swing.JPanel {

    /**
     * Creates new form UsersPanel
     */
    public DriversPanel() {
        initComponents();
    }

    private MiddlePanel middlePanel = new MiddlePanel();
    private DriverQuery driverQuery = new DriverQuery();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonScrollPane = new javax.swing.JScrollPane();
        buttonPanel = new javax.swing.JPanel();
        getBusByIdButton = new javax.swing.JButton();
        getAllBusesButton = new javax.swing.JButton();
        getTripsWithBusButton = new javax.swing.JButton();
        updateBusButton = new javax.swing.JButton();
        createBusButton = new javax.swing.JButton();
        deleteBusrButton = new javax.swing.JButton();
        deleteBusrButton1 = new javax.swing.JButton();
        tableScrollPane = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(943, 545));
        setMinimumSize(new java.awt.Dimension(943, 545));

        buttonScrollPane.setBackground(new java.awt.Color(220, 220, 220));
        buttonScrollPane.setForeground(new java.awt.Color(220, 220, 220));
        buttonScrollPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonScrollPane.setHorizontalScrollBar(null);

        buttonPanel.setMaximumSize(new java.awt.Dimension(85, 33));
        buttonPanel.setName(""); // NOI18N
        buttonPanel.setLayout(new javax.swing.BoxLayout(buttonPanel, javax.swing.BoxLayout.Y_AXIS));

        getBusByIdButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getBusByIdButton.setText("Get Driver By ID");
        getBusByIdButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getBusByIdButton.setMaximumSize(new java.awt.Dimension(180, 40));
        getBusByIdButton.setMinimumSize(new java.awt.Dimension(180, 40));
        getBusByIdButton.setPreferredSize(new java.awt.Dimension(180, 40));
        getBusByIdButton.addActionListener(this::getBusByIdButtonActionPerformed);
        buttonPanel.add(getBusByIdButton);

        getAllBusesButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getAllBusesButton.setText("Get All Drivers");
        getAllBusesButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getAllBusesButton.setMaximumSize(new java.awt.Dimension(180, 40));
        getAllBusesButton.setMinimumSize(new java.awt.Dimension(180, 40));
        getAllBusesButton.setPreferredSize(new java.awt.Dimension(180, 40));
        getAllBusesButton.addActionListener(this::getAllBusesButtonActionPerformed);
        buttonPanel.add(getAllBusesButton);

        getTripsWithBusButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getTripsWithBusButton.setText(" Get Buses Driven");
        getTripsWithBusButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getTripsWithBusButton.setMaximumSize(new java.awt.Dimension(180, 40));
        getTripsWithBusButton.setMinimumSize(new java.awt.Dimension(180, 40));
        getTripsWithBusButton.setPreferredSize(new java.awt.Dimension(180, 40));
        getTripsWithBusButton.addActionListener(this::getTripsWithBusButtonActionPerformed);
        buttonPanel.add(getTripsWithBusButton);

        updateBusButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        updateBusButton.setText("Get Trips Driven");
        updateBusButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        updateBusButton.setMaximumSize(new java.awt.Dimension(180, 40));
        updateBusButton.setMinimumSize(new java.awt.Dimension(180, 40));
        updateBusButton.setPreferredSize(new java.awt.Dimension(180, 40));
        updateBusButton.addActionListener(this::updateBusButtonActionPerformed);
        buttonPanel.add(updateBusButton);

        createBusButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        createBusButton.setText("Create Driver");
        createBusButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        createBusButton.setMaximumSize(new java.awt.Dimension(180, 40));
        createBusButton.setMinimumSize(new java.awt.Dimension(180, 40));
        createBusButton.setPreferredSize(new java.awt.Dimension(180, 40));
        createBusButton.addActionListener(this::createBusButtonActionPerformed);
        buttonPanel.add(createBusButton);

        deleteBusrButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteBusrButton.setText("Update Driver");
        deleteBusrButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        deleteBusrButton.setMaximumSize(new java.awt.Dimension(180, 40));
        deleteBusrButton.setMinimumSize(new java.awt.Dimension(180, 40));
        deleteBusrButton.setPreferredSize(new java.awt.Dimension(180, 40));
        deleteBusrButton.addActionListener(this::deleteBusrButtonActionPerformed);
        buttonPanel.add(deleteBusrButton);

        deleteBusrButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteBusrButton1.setText("Delete Driver");
        deleteBusrButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        deleteBusrButton1.setMaximumSize(new java.awt.Dimension(180, 40));
        deleteBusrButton1.setMinimumSize(new java.awt.Dimension(180, 40));
        deleteBusrButton1.setPreferredSize(new java.awt.Dimension(180, 40));
        deleteBusrButton1.addActionListener(this::deleteBusrButton1ActionPerformed);
        buttonPanel.add(deleteBusrButton1);

        buttonScrollPane.setViewportView(buttonPanel);

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableScrollPane.setViewportView(resultTable);

        headerPanel.setLayout(new java.awt.CardLayout());

        headerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("DRIVERS");
        headerPanel.add(headerLabel, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 201, Short.MAX_VALUE)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(buttonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 747, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 64, Short.MAX_VALUE)
                    .addComponent(buttonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateBusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBusButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateBusButtonActionPerformed

    private void getBusByIdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getBusByIdButtonActionPerformed
        String input = javax.swing.JOptionPane.showInputDialog(this, "Enter DriverID:", "Find Driver", javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (input == null) return;
        input = input.trim();
        if (input.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "DriverID cannot be empty.", "Input error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int driverId;
        try {
            driverId = Integer.parseInt(input);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid numeric DriverID.", "Input error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            java.util.Map<String, Object> drv = driverQuery.getDriverById(driverId);
            if (drv == null || drv.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "No driver found with ID: " + driverId, "Not found", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                resultTable.setModel(new javax.swing.table.DefaultTableModel());
                return;
            }
            java.util.List<java.util.Map<String, Object>> rows = new java.util.ArrayList<>();
            rows.add(drv);
            middlePanel.setTableContents(resultTable, rows);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error fetching driver: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_getBusByIdButtonActionPerformed

    private void getAllBusesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAllBusesButtonActionPerformed
        middlePanel.setTableContents(resultTable, driverQuery.getAllDrivers());
    }//GEN-LAST:event_getAllBusesButtonActionPerformed

    private void getTripsWithBusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getTripsWithBusButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getTripsWithBusButtonActionPerformed

    private void createBusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBusButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createBusButtonActionPerformed

    private void deleteBusrButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBusrButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBusrButtonActionPerformed

    private void deleteBusrButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBusrButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBusrButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JScrollPane buttonScrollPane;
    private javax.swing.JButton createBusButton;
    private javax.swing.JButton deleteBusrButton;
    private javax.swing.JButton deleteBusrButton1;
    private javax.swing.JButton getAllBusesButton;
    private javax.swing.JButton getBusByIdButton;
    private javax.swing.JButton getTripsWithBusButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JTable resultTable;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JButton updateBusButton;
    // End of variables declaration//GEN-END:variables
}
