/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.buspass.gui.app_gui.admin;

import com.buspass.queries.DriverQuery;

/**
 *
 * @author USER
 */
public class DriversPanel extends javax.swing.JPanel {

    /**
     * Creates new form UsersPanel
     */
    public DriversPanel() {
        initComponents();
    }

    private MiddlePanel middlePanel = new MiddlePanel();
    private DriverQuery driverQuery = new DriverQuery();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonScrollPane = new javax.swing.JScrollPane();
        buttonPanel = new javax.swing.JPanel();
        getBusByIdButton = new javax.swing.JButton();
        getAllBusesButton = new javax.swing.JButton();
        getTripsWithBusButton = new javax.swing.JButton();
        getTripsDrivenButton = new javax.swing.JButton();
        createDriverButton = new javax.swing.JButton();
        updateDriverButton = new javax.swing.JButton();
        deleteDriverButton = new javax.swing.JButton();
        tableScrollPane = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(943, 545));
        setMinimumSize(new java.awt.Dimension(943, 545));

        buttonScrollPane.setBackground(new java.awt.Color(220, 220, 220));
        buttonScrollPane.setForeground(new java.awt.Color(220, 220, 220));
        buttonScrollPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonScrollPane.setHorizontalScrollBar(null);

        buttonPanel.setMaximumSize(new java.awt.Dimension(85, 33));
        buttonPanel.setName(""); // NOI18N
        buttonPanel.setLayout(new javax.swing.BoxLayout(buttonPanel, javax.swing.BoxLayout.Y_AXIS));

        getBusByIdButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getBusByIdButton.setText("Get Driver By ID");
        getBusByIdButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getBusByIdButton.setMaximumSize(new java.awt.Dimension(180, 40));
        getBusByIdButton.setMinimumSize(new java.awt.Dimension(180, 40));
        getBusByIdButton.setPreferredSize(new java.awt.Dimension(180, 40));
        getBusByIdButton.addActionListener(this::getBusByIdButtonActionPerformed);
        buttonPanel.add(getBusByIdButton);

        getAllBusesButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getAllBusesButton.setText("Get All Drivers");
        getAllBusesButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getAllBusesButton.setMaximumSize(new java.awt.Dimension(180, 40));
        getAllBusesButton.setMinimumSize(new java.awt.Dimension(180, 40));
        getAllBusesButton.setPreferredSize(new java.awt.Dimension(180, 40));
        getAllBusesButton.addActionListener(this::getAllBusesButtonActionPerformed);
        buttonPanel.add(getAllBusesButton);

        getTripsWithBusButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getTripsWithBusButton.setText(" Get Buses Driven");
        getTripsWithBusButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getTripsWithBusButton.setMaximumSize(new java.awt.Dimension(180, 40));
        getTripsWithBusButton.setMinimumSize(new java.awt.Dimension(180, 40));
        getTripsWithBusButton.setPreferredSize(new java.awt.Dimension(180, 40));
        getTripsWithBusButton.addActionListener(this::getTripsWithBusButtonActionPerformed);
        buttonPanel.add(getTripsWithBusButton);

        getTripsDrivenButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getTripsDrivenButton.setText("Get Trips Driven");
        getTripsDrivenButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getTripsDrivenButton.setMaximumSize(new java.awt.Dimension(180, 40));
        getTripsDrivenButton.setMinimumSize(new java.awt.Dimension(180, 40));
        getTripsDrivenButton.setPreferredSize(new java.awt.Dimension(180, 40));
        getTripsDrivenButton.addActionListener(this::getTripsDrivenButtonActionPerformed);
        buttonPanel.add(getTripsDrivenButton);

        createDriverButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        createDriverButton.setText("Create Driver");
        createDriverButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        createDriverButton.setMaximumSize(new java.awt.Dimension(180, 40));
        createDriverButton.setMinimumSize(new java.awt.Dimension(180, 40));
        createDriverButton.setPreferredSize(new java.awt.Dimension(180, 40));
        createDriverButton.addActionListener(this::createDriverButtonActionPerformed);
        buttonPanel.add(createDriverButton);

        updateDriverButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        updateDriverButton.setText("Update Driver");
        updateDriverButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        updateDriverButton.setMaximumSize(new java.awt.Dimension(180, 40));
        updateDriverButton.setMinimumSize(new java.awt.Dimension(180, 40));
        updateDriverButton.setPreferredSize(new java.awt.Dimension(180, 40));
        updateDriverButton.addActionListener(this::updateDriverButtonActionPerformed);
        buttonPanel.add(updateDriverButton);

        deleteDriverButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteDriverButton.setText("Delete Driver");
        deleteDriverButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        deleteDriverButton.setMaximumSize(new java.awt.Dimension(180, 40));
        deleteDriverButton.setMinimumSize(new java.awt.Dimension(180, 40));
        deleteDriverButton.setPreferredSize(new java.awt.Dimension(180, 40));
        deleteDriverButton.addActionListener(this::deleteDriverButtonActionPerformed);
        buttonPanel.add(deleteDriverButton);

        buttonScrollPane.setViewportView(buttonPanel);

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableScrollPane.setViewportView(resultTable);

        headerPanel.setLayout(new java.awt.CardLayout());

        headerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("DRIVERS");
        headerPanel.add(headerLabel, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 201, Short.MAX_VALUE)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(buttonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 747, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 64, Short.MAX_VALUE)
                    .addComponent(buttonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void getTripsDrivenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getTripsDrivenButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getTripsDrivenButtonActionPerformed

    private void getBusByIdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getBusByIdButtonActionPerformed
        String input = javax.swing.JOptionPane.showInputDialog(this, "Enter DriverID:", "Find Driver", javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (input == null) return;
        input = input.trim();
        if (input.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "DriverID cannot be empty.", "Input error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int driverId;
        try {
            driverId = Integer.parseInt(input);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid numeric DriverID.", "Input error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            java.util.Map<String, Object> drv = driverQuery.getDriverById(driverId);
            if (drv == null || drv.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "No driver found with ID: " + driverId, "Not found", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                resultTable.setModel(new javax.swing.table.DefaultTableModel());
                return;
            }
            java.util.List<java.util.Map<String, Object>> rows = new java.util.ArrayList<>();
            rows.add(drv);
            middlePanel.setTableContents(resultTable, rows);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error fetching driver: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_getBusByIdButtonActionPerformed

    private void getAllBusesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAllBusesButtonActionPerformed
        middlePanel.setTableContents(resultTable, driverQuery.getAllDrivers());
    }//GEN-LAST:event_getAllBusesButtonActionPerformed

    private void getTripsWithBusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getTripsWithBusButtonActionPerformed
        String input = javax.swing.JOptionPane.showInputDialog(this, "Enter DriverID to list buses driven:", "Buses Driven", javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (input == null) return;
        input = input.trim();
        if (input.isEmpty()) { javax.swing.JOptionPane.showMessageDialog(this, "DriverID cannot be empty.", "Input error", javax.swing.JOptionPane.WARNING_MESSAGE); return; }
        int driverId; try { driverId = Integer.parseInt(input); } catch (NumberFormatException e) { javax.swing.JOptionPane.showMessageDialog(this, "Invalid DriverID.", "Input error", javax.swing.JOptionPane.ERROR_MESSAGE); return; }
        try { middlePanel.setTableContents(resultTable, driverQuery.getAllDrivenBuses(driverId)); } catch (Exception ex) { javax.swing.JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE); ex.printStackTrace(); }
    }//GEN-LAST:event_getTripsWithBusButtonActionPerformed

    private void createDriverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDriverButtonActionPerformed
        String name = javax.swing.JOptionPane.showInputDialog(this, "Driver name:", "Create Driver", javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (name == null) return; name = name.trim(); if (name.isEmpty()) { javax.swing.JOptionPane.showMessageDialog(this, "Name required.", "Input", javax.swing.JOptionPane.WARNING_MESSAGE); return; }
        String ageStr = javax.swing.JOptionPane.showInputDialog(this, "Age:", "Create Driver", javax.swing.JOptionPane.QUESTION_MESSAGE); if (ageStr == null) return; int age; try { age = Integer.parseInt(ageStr.trim()); } catch (NumberFormatException e) { javax.swing.JOptionPane.showMessageDialog(this, "Invalid age.", "Input error", javax.swing.JOptionPane.ERROR_MESSAGE); return; }
        String license = javax.swing.JOptionPane.showInputDialog(this, "License:", "Create Driver", javax.swing.JOptionPane.QUESTION_MESSAGE); if (license == null) return;
        String phone = javax.swing.JOptionPane.showInputDialog(this, "Phone:", "Create Driver", javax.swing.JOptionPane.QUESTION_MESSAGE); if (phone == null) return;
        try { boolean ok = driverQuery.registerDriver(name, age, license.trim(), phone.trim()); if (ok) { javax.swing.JOptionPane.showMessageDialog(this, "Driver created.", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE); middlePanel.setTableContents(resultTable, driverQuery.getAllDrivers()); } else { javax.swing.JOptionPane.showMessageDialog(this, "Failed to create driver.", "Failure", javax.swing.JOptionPane.ERROR_MESSAGE); } } catch (Exception ex) { javax.swing.JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE); ex.printStackTrace(); }
    }//GEN-LAST:event_createDriverButtonActionPerformed

    private void updateDriverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDriverButtonActionPerformed
        // This button is labelled 'Update Driver' in the UI; leave for update flows.
    }//GEN-LAST:event_updateDriverButtonActionPerformed

    private void deleteDriverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDriverButtonActionPerformed
        String input = javax.swing.JOptionPane.showInputDialog(this, "Enter DriverID to delete:", "Delete Driver", javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (input == null) return; input = input.trim(); if (input.isEmpty()) { javax.swing.JOptionPane.showMessageDialog(this, "DriverID cannot be empty.", "Input error", javax.swing.JOptionPane.WARNING_MESSAGE); return; }
        int driverId; try { driverId = Integer.parseInt(input); } catch (NumberFormatException e) { javax.swing.JOptionPane.showMessageDialog(this, "Invalid DriverID.", "Input error", javax.swing.JOptionPane.ERROR_MESSAGE); return; }
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Delete DriverID " + driverId + "?", "Confirm", javax.swing.JOptionPane.YES_NO_OPTION); if (confirm != javax.swing.JOptionPane.YES_OPTION) return;
        try { boolean ok = driverQuery.deleteDriverById(driverId); if (ok) { javax.swing.JOptionPane.showMessageDialog(this, "Driver deleted.", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE); middlePanel.setTableContents(resultTable, driverQuery.getAllDrivers()); } else { javax.swing.JOptionPane.showMessageDialog(this, "Driver not found or failed to delete.", "Failure", javax.swing.JOptionPane.ERROR_MESSAGE); } } catch (Exception ex) { javax.swing.JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE); ex.printStackTrace(); }
    }//GEN-LAST:event_deleteDriverButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JScrollPane buttonScrollPane;
    private javax.swing.JButton createDriverButton;
    private javax.swing.JButton deleteDriverButton;
    private javax.swing.JButton getAllBusesButton;
    private javax.swing.JButton getBusByIdButton;
    private javax.swing.JButton getTripsDrivenButton;
    private javax.swing.JButton getTripsWithBusButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JTable resultTable;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JButton updateDriverButton;
    // End of variables declaration//GEN-END:variables
}
