/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.buspass.gui.app_gui.admin;

import com.buspass.queries.BusQuery;

/**
 *
 * @author USER
 */
public class PaymentsPanel extends javax.swing.JPanel {

    /**
     * Creates new form UsersPanel
     */
    public PaymentsPanel() {
        initComponents();
    }

    private MiddlePanel middlePanel = new MiddlePanel();
    private BusQuery busQuery = new BusQuery();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonScrollPane = new javax.swing.JScrollPane();
        buttonPanel = new javax.swing.JPanel();
        myPaymentsButton = new javax.swing.JButton();
        getPaymentsOfUserButton = new javax.swing.JButton();
        createTransactionButton = new javax.swing.JButton();
        deletePaymentButton = new javax.swing.JButton();
        tableScrollPane = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(943, 545));
        setMinimumSize(new java.awt.Dimension(943, 545));

        buttonScrollPane.setBackground(new java.awt.Color(220, 220, 220));
        buttonScrollPane.setForeground(new java.awt.Color(220, 220, 220));
        buttonScrollPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonScrollPane.setHorizontalScrollBar(null);

        buttonPanel.setMaximumSize(new java.awt.Dimension(85, 33));
        buttonPanel.setName(""); // NOI18N
        buttonPanel.setLayout(new javax.swing.BoxLayout(buttonPanel, javax.swing.BoxLayout.Y_AXIS));

        myPaymentsButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        myPaymentsButton.setText("My Payments");
        myPaymentsButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        myPaymentsButton.setMaximumSize(new java.awt.Dimension(180, 40));
        myPaymentsButton.setMinimumSize(new java.awt.Dimension(180, 40));
        myPaymentsButton.setPreferredSize(new java.awt.Dimension(180, 40));
        myPaymentsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myPaymentsButtonMouseClicked(evt);
            }
        });
        myPaymentsButton.addActionListener(this::myPaymentsButtonActionPerformed);
        buttonPanel.add(myPaymentsButton);

        getPaymentsOfUserButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getPaymentsOfUserButton.setText("Get Payments Of User");
        getPaymentsOfUserButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getPaymentsOfUserButton.setMaximumSize(new java.awt.Dimension(180, 40));
        getPaymentsOfUserButton.setMinimumSize(new java.awt.Dimension(180, 40));
        getPaymentsOfUserButton.setPreferredSize(new java.awt.Dimension(180, 40));
        getPaymentsOfUserButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getPaymentsOfUserButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(getPaymentsOfUserButton);

        createTransactionButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        createTransactionButton.setText("Create Transaction");
        createTransactionButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        createTransactionButton.setMaximumSize(new java.awt.Dimension(180, 40));
        createTransactionButton.setMinimumSize(new java.awt.Dimension(180, 40));
        createTransactionButton.setPreferredSize(new java.awt.Dimension(180, 40));
        createTransactionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createTransactionButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(createTransactionButton);

        deletePaymentButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deletePaymentButton.setText("Delete Payment");
        deletePaymentButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        deletePaymentButton.setMaximumSize(new java.awt.Dimension(180, 40));
        deletePaymentButton.setMinimumSize(new java.awt.Dimension(180, 40));
        deletePaymentButton.setPreferredSize(new java.awt.Dimension(180, 40));
        deletePaymentButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletePaymentButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(deletePaymentButton);

        buttonScrollPane.setViewportView(buttonPanel);

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableScrollPane.setViewportView(resultTable);

        headerPanel.setLayout(new java.awt.GridBagLayout());

        headerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("PAYMENTS");
        headerPanel.add(headerLabel, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 201, Short.MAX_VALUE)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(buttonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 747, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 64, Short.MAX_VALUE)
                    .addComponent(buttonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void myPaymentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myPaymentsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myPaymentsButtonActionPerformed

    private void myPaymentsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myPaymentsButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_myPaymentsButtonMouseClicked

    private void getPaymentsOfUserButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getPaymentsOfUserButtonMouseClicked
        middlePanel.setTableContents(resultTable, busQuery.getAllBuses());
    }//GEN-LAST:event_getPaymentsOfUserButtonMouseClicked

    private void createTransactionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createTransactionButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_createTransactionButtonMouseClicked

    private void deletePaymentButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletePaymentButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deletePaymentButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JScrollPane buttonScrollPane;
    private javax.swing.JButton createTransactionButton;
    private javax.swing.JButton deletePaymentButton;
    private javax.swing.JButton getPaymentsOfUserButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton myPaymentsButton;
    private javax.swing.JTable resultTable;
    private javax.swing.JScrollPane tableScrollPane;
    // End of variables declaration//GEN-END:variables
}
