/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.buspass.gui.app_gui.admin;

import com.buspass.queries.BusQuery;
import com.buspass.queries.UserService;

/**
 *
 * @author USER
 */
public class TicketsPanel extends javax.swing.JPanel {

    /**
     * Creates new form UsersPanel
     */
    public TicketsPanel() {
        initComponents();
    }

    private MiddlePanel middlePanel = new MiddlePanel();
    private BusQuery busQuery = new BusQuery();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonScrollPane = new javax.swing.JScrollPane();
        buttonPanel = new javax.swing.JPanel();
        buyTicketButton = new javax.swing.JButton();
        myTicketsButton = new javax.swing.JButton();
        changeToTripButton = new javax.swing.JButton();
        getTicketsOfUserButton = new javax.swing.JButton();
        deleteTicket = new javax.swing.JButton();
        tableScrollPane = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(943, 545));
        setMinimumSize(new java.awt.Dimension(943, 545));

        buttonScrollPane.setBackground(new java.awt.Color(220, 220, 220));
        buttonScrollPane.setForeground(new java.awt.Color(220, 220, 220));
        buttonScrollPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonScrollPane.setHorizontalScrollBar(null);

        buttonPanel.setMaximumSize(new java.awt.Dimension(85, 33));
        buttonPanel.setName(""); // NOI18N
        buttonPanel.setLayout(new javax.swing.BoxLayout(buttonPanel, javax.swing.BoxLayout.Y_AXIS));

        buyTicketButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buyTicketButton.setText("Buy Ticket");
        buyTicketButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buyTicketButton.setMaximumSize(new java.awt.Dimension(180, 40));
        buyTicketButton.setMinimumSize(new java.awt.Dimension(180, 40));
        buyTicketButton.setPreferredSize(new java.awt.Dimension(180, 40));
        buyTicketButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buyTicketButtonMouseClicked(evt);
            }
        });
        buyTicketButton.addActionListener(this::buyTicketButtonActionPerformed);
        buttonPanel.add(buyTicketButton);

        myTicketsButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        myTicketsButton.setText("My Tickets");
        myTicketsButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        myTicketsButton.setMaximumSize(new java.awt.Dimension(180, 40));
        myTicketsButton.setMinimumSize(new java.awt.Dimension(180, 40));
        myTicketsButton.setPreferredSize(new java.awt.Dimension(180, 40));
        myTicketsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myTicketsButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(myTicketsButton);

        changeToTripButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        changeToTripButton.setText("Change Ticket Trip");
        changeToTripButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        changeToTripButton.setMaximumSize(new java.awt.Dimension(180, 40));
        changeToTripButton.setMinimumSize(new java.awt.Dimension(180, 40));
        changeToTripButton.setPreferredSize(new java.awt.Dimension(180, 40));
        changeToTripButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeToTripButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(changeToTripButton);

        getTicketsOfUserButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getTicketsOfUserButton.setText("Get Tickets Of User");
        getTicketsOfUserButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getTicketsOfUserButton.setMaximumSize(new java.awt.Dimension(180, 40));
        getTicketsOfUserButton.setMinimumSize(new java.awt.Dimension(180, 40));
        getTicketsOfUserButton.setPreferredSize(new java.awt.Dimension(180, 40));
        getTicketsOfUserButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getTicketsOfUserButtonMouseClicked(evt);
            }
        });
        getTicketsOfUserButton.addActionListener(this::getTicketsOfUserButtonActionPerformed);
        buttonPanel.add(getTicketsOfUserButton);

        deleteTicket.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteTicket.setText("Remove Ticket");
        deleteTicket.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        deleteTicket.setMaximumSize(new java.awt.Dimension(180, 40));
        deleteTicket.setMinimumSize(new java.awt.Dimension(180, 40));
        deleteTicket.setPreferredSize(new java.awt.Dimension(180, 40));
        deleteTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteTicketMouseClicked(evt);
            }
        });
        buttonPanel.add(deleteTicket);

        buttonScrollPane.setViewportView(buttonPanel);

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableScrollPane.setViewportView(resultTable);

        headerPanel.setLayout(new java.awt.GridBagLayout());

        headerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("TICKETS");
        headerPanel.add(headerLabel, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 201, Short.MAX_VALUE)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(buttonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 747, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 64, Short.MAX_VALUE)
                    .addComponent(buttonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void getTicketsOfUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getTicketsOfUserButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getTicketsOfUserButtonActionPerformed

    private void buyTicketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyTicketButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buyTicketButtonActionPerformed

    private void buyTicketButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyTicketButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buyTicketButtonMouseClicked

    private void myTicketsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myTicketsButtonMouseClicked
        middlePanel.setTableContents(resultTable, busQuery.getAllBuses());
    }//GEN-LAST:event_myTicketsButtonMouseClicked

    private void getTicketsOfUserButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getTicketsOfUserButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_getTicketsOfUserButtonMouseClicked

    private void changeToTripButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeToTripButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_changeToTripButtonMouseClicked

    private void deleteTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteTicketMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteTicketMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JScrollPane buttonScrollPane;
    private javax.swing.JButton buyTicketButton;
    private javax.swing.JButton changeToTripButton;
    private javax.swing.JButton deleteTicket;
    private javax.swing.JButton getTicketsOfUserButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton myTicketsButton;
    private javax.swing.JTable resultTable;
    private javax.swing.JScrollPane tableScrollPane;
    // End of variables declaration//GEN-END:variables
}
