/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.buspass.gui.app_gui.admin;

import com.buspass.queries.UserService;

/**
 *
 * @author USER
 */
public class UsersPanel extends javax.swing.JPanel {

    /**
     * Creates new form UsersPanel
     */
    public UsersPanel() {
        initComponents();
    }

    private MiddlePanel middlePanel = new MiddlePanel();
    private UserService userService = new UserService();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonScrollPane = new javax.swing.JScrollPane();
        buttonPanel = new javax.swing.JPanel();
        getUserByIdButton = new javax.swing.JButton();
        getAllUsersButton = new javax.swing.JButton();
        updateUserButton = new javax.swing.JButton();
        createUserButton = new javax.swing.JButton();
        findIdButton = new javax.swing.JButton();
        deleteUserButton = new javax.swing.JButton();
        tableScrollPane = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(943, 545));
        setMinimumSize(new java.awt.Dimension(943, 545));

        buttonScrollPane.setBackground(new java.awt.Color(220, 220, 220));
        buttonScrollPane.setForeground(new java.awt.Color(220, 220, 220));
        buttonScrollPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonScrollPane.setHorizontalScrollBar(null);

        buttonPanel.setMaximumSize(new java.awt.Dimension(85, 33));
        buttonPanel.setName(""); // NOI18N
        buttonPanel.setLayout(new javax.swing.BoxLayout(buttonPanel, javax.swing.BoxLayout.Y_AXIS));

        getUserByIdButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getUserByIdButton.setText("Get User By ID");
        getUserByIdButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getUserByIdButton.setMaximumSize(new java.awt.Dimension(180, 40));
        getUserByIdButton.setMinimumSize(new java.awt.Dimension(180, 40));
        getUserByIdButton.setPreferredSize(new java.awt.Dimension(180, 40));
        getUserByIdButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getUserByIdButtonMouseClicked(evt);
            }
        });
        getUserByIdButton.addActionListener(this::getUserByIdButtonActionPerformed);
        buttonPanel.add(getUserByIdButton);

        getAllUsersButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getAllUsersButton.setText("Get All Users");
        getAllUsersButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getAllUsersButton.setMaximumSize(new java.awt.Dimension(180, 40));
        getAllUsersButton.setMinimumSize(new java.awt.Dimension(180, 40));
        getAllUsersButton.setPreferredSize(new java.awt.Dimension(180, 40));
        getAllUsersButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getAllUsersButtonMouseClicked(evt);
            }
        });
        getAllUsersButton.addActionListener(this::getAllUsersButtonActionPerformed);
        buttonPanel.add(getAllUsersButton);

        updateUserButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        updateUserButton.setText("Update User");
        updateUserButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        updateUserButton.setMaximumSize(new java.awt.Dimension(180, 40));
        updateUserButton.setMinimumSize(new java.awt.Dimension(180, 40));
        updateUserButton.setPreferredSize(new java.awt.Dimension(180, 40));
        updateUserButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateUserButtonMouseClicked(evt);
            }
        });
        updateUserButton.addActionListener(this::updateUserButtonActionPerformed);
        buttonPanel.add(updateUserButton);

        createUserButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        createUserButton.setText("Create User");
        createUserButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        createUserButton.setMaximumSize(new java.awt.Dimension(180, 40));
        createUserButton.setMinimumSize(new java.awt.Dimension(180, 40));
        createUserButton.setPreferredSize(new java.awt.Dimension(180, 40));
        createUserButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createUserButtonMouseClicked(evt);
            }
        });
        createUserButton.addActionListener(this::createUserButtonActionPerformed);
        buttonPanel.add(createUserButton);

        findIdButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        findIdButton.setText("Find UserID By Username");
        findIdButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        findIdButton.setMaximumSize(new java.awt.Dimension(180, 40));
        findIdButton.setMinimumSize(new java.awt.Dimension(180, 40));
        findIdButton.setPreferredSize(new java.awt.Dimension(180, 40));
        findIdButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                findIdButtonMouseClicked(evt);
            }
        });
        findIdButton.addActionListener(this::findIdButtonActionPerformed);
        buttonPanel.add(findIdButton);

        deleteUserButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteUserButton.setText("Delete User");
        deleteUserButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        deleteUserButton.setMaximumSize(new java.awt.Dimension(180, 40));
        deleteUserButton.setMinimumSize(new java.awt.Dimension(180, 40));
        deleteUserButton.setPreferredSize(new java.awt.Dimension(180, 40));
        deleteUserButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteUserButtonMouseClicked(evt);
            }
        });
        deleteUserButton.addActionListener(this::deleteUserButtonActionPerformed);
        buttonPanel.add(deleteUserButton);

        buttonScrollPane.setViewportView(buttonPanel);

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableScrollPane.setViewportView(resultTable);

        headerPanel.setLayout(new java.awt.CardLayout());

        headerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("USERS");
        headerPanel.add(headerLabel, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(buttonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 747, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 64, Short.MAX_VALUE)
                    .addComponent(buttonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateUserButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateUserButtonActionPerformed

    private void getUserByIdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getUserByIdButtonActionPerformed
        // Super temporary solution for retriving User

        String input = javax.swing.JOptionPane.showInputDialog(this, "Enter UserID:", "Find User", javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (input == null) return; // user cancelled
        input = input.trim();
        if (input.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "UserID cannot be empty.", "Input error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int userId;
        try {
            userId = Integer.parseInt(input);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid numeric UserID.", "Input error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            java.util.Map<String, Object> user = userService.getUserById(userId);
            if (user == null || user.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "No user found with ID: " + userId, "Not found", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                resultTable.setModel(new javax.swing.table.DefaultTableModel());
                return;
            }

            java.util.List<java.util.Map<String, Object>> rows = new java.util.ArrayList<>();
            rows.add(user);
            middlePanel.setTableContents(resultTable, rows);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error fetching user: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_getUserByIdButtonActionPerformed

    private void getUserByIdButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getUserByIdButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_getUserByIdButtonMouseClicked

    private void getAllUsersButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getAllUsersButtonMouseClicked
    }//GEN-LAST:event_getAllUsersButtonMouseClicked

    private void updateUserButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateUserButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_updateUserButtonMouseClicked

    private void createUserButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createUserButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_createUserButtonMouseClicked

    private void findIdButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findIdButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_findIdButtonMouseClicked

    private void deleteUserButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteUserButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteUserButtonMouseClicked

    private void getAllUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAllUsersButtonActionPerformed
        middlePanel.setTableContents(resultTable, userService.getAllUsers());
    }//GEN-LAST:event_getAllUsersButtonActionPerformed

    private void createUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createUserButtonActionPerformed

    private void findIdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findIdButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findIdButtonActionPerformed

    private void deleteUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteUserButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JScrollPane buttonScrollPane;
    private javax.swing.JButton createUserButton;
    private javax.swing.JButton deleteUserButton;
    private javax.swing.JButton findIdButton;
    private javax.swing.JButton getAllUsersButton;
    private javax.swing.JButton getUserByIdButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JTable resultTable;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JButton updateUserButton;
    // End of variables declaration//GEN-END:variables
}
